import type { Deck, Slide } from '../../../shared/types';

// ──────────────────────────────────────────────────────────────
//  경남항공고 AI 특강 덱 — 항공 특성화고 학생 300명(강당, 스마트폰 참여)
//  50분 × 3교시: 1교시 생성형 AI·바이브코딩 / 2교시 AI 윤리 / 3교시 항공 AI 진로
//  바이브코딩은 교시마다 같은 앱을 이어서 키움 (Lv.1 new → Lv.2·Lv.3 continue)
//  슬라이드 문구는 명사형 개조식, 노트는 강사용 진행 메모 (≤400자 — validate.ts)
//  레지스트리 미등록 — DB 시드로 탑재
// ──────────────────────────────────────────────────────────────

export const gyeongnamAviation3h: Deck = {
  id: 'gnaero',
  title: '경남항공고 AI 특강 — 바이브코딩 · AI 윤리 · 항공 AI 진로',
  activities: {
    // ── 0. 입장·워밍업 ──
    'poll-warmup': {
      type: 'poll',
      id: 'poll-warmup',
      title: '워밍업 워드클라우드',
      prompt: 'AI 하면 떠오르는 단어 하나',
      mode: 'wordcloud',
      anonymous: true,
    },
    'quiz-warmup': {
      type: 'quiz',
      id: 'quiz-warmup',
      title: '워밍업 OX 퀴즈',
      intro: '몸풀기 3문항 · 빠르고 정확하게',
      questions: [
        {
          id: 'w1',
          question: 'ChatGPT 같은 생성형 AI는 정답을 인터넷에서 검색해서 그대로 가져온다?',
          options: ['O', 'X'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '검색 복사 아님 · 학습한 패턴으로 다음에 올 말을 확률로 예측해 생성',
        },
        {
          id: 'w2',
          question: 'AI는 틀린 내용을 사실처럼 자신 있게 말할 때가 있다?',
          options: ['O', 'X'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '환각(Hallucination) · 그럴듯하지만 사실이 아닌 답 → 사람의 검증 필요',
        },
        {
          id: 'w3',
          question: '코드를 한 줄도 몰라도 말로 설명해서 앱을 만들 수 있다?',
          options: ['O', 'X'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '바이브코딩(Vibe Coding) · 원하는 기능을 말로 설명 → AI가 코드 작성 · 오늘 1교시 실습 내용',
        },
      ],
    },

    // ── 1교시. 생성형 AI와 바이브코딩 ──
    'image-future-aircraft': {
      type: 'image',
      id: 'image-future-aircraft',
      maxImages: 2,
      title: '2040년 미래 항공기 그리기',
      intro: '장면 · 분위기 · 스타일을 글로 묘사 → AI가 이미지로 생성 · 1인 2장',
      suggestions: [
        '도심 빌딩 사이를 나는 전기 수직이착륙기(UAM), 해 질 녘, 디지털 아트',
        '구름 위를 나는 날개와 동체가 하나로 합쳐진 미래 여객기, 사실적인 사진 스타일',
        '격납고 안 정비 로봇과 함께 점검 중인 미래 항공기, 밝은 조명, 3D 렌더링',
        '사막 위 태양광 날개를 단 무인 드론 편대, 수채화 스타일',
        '우주와 대기권 경계를 나는 초음속 여객기, 푸른 지구 배경, 일러스트',
      ],
    },
    'vibe-lv1': {
      type: 'vibe',
      id: 'vibe-lv1',
      title: '바이브코딩 Lv.1 — 나의 첫 항공 앱',
      intro: '만들고 싶은 앱을 말로 설명 → AI가 폰에서 바로 도는 앱 생성 · 결과 확인 후 한 번에 하나씩 수정',
      task:
        '항공 현장이나 학교생활에 쓸 수 있는 나만의 첫 앱 만들기. 누가 쓰는지 · 무엇을 하는지 · 화면이 어떻게 보이는지 세 가지를 넣어 설명. 완성 후 "버튼 색 바꿔줘"처럼 한 번에 하나씩 수정 요청.',
      ideas: [
        '항공기 외부 점검(Walk-around) 체크리스트 앱 — 항목 체크하면 진행률 표시',
        '토크 단위 변환기 — in-lb, ft-lb, N·m 서로 변환',
        '항공 음성 알파벳(Alpha, Bravo…) 암기 퀴즈 앱',
        '비행기 부품 이름 맞히기 퀴즈 — 점수와 정답 해설 표시',
        '항공 정비 공구 대여 기록장 — 공구 이름과 반납 여부 체크',
        '공항 3글자 코드(ICN, GMP, PUS…) 맞히기 게임',
      ],
      continueMode: 'new',
      maxBuilds: 6,
    },

    // ── 2교시. AI 윤리 ──
    'ox-hallucination': {
      type: 'ox',
      id: 'ox-hallucination',
      title: '환각 OX — 정비 매뉴얼 수치',
      question: 'AI가 알려준 볼트 조임 토크 값이 그럴듯하다. 정비 매뉴얼 확인 없이 바로 작업해도 된다?',
      answer: 'X',
      timeLimitSec: 20,
      explanation: 'AI는 존재하지 않는 수치도 그럴듯하게 생성 가능 · 정비 수치는 반드시 승인된 정비 매뉴얼로 확인',
    },
    'image-real-or-fake': {
      type: 'image',
      id: 'image-real-or-fake',
      maxImages: 2,
      title: '진짜일까 가짜일까 — 가짜 사진 만들기 체험',
      intro: '실제로 없는 장면을 사진처럼 생성 → 가짜 사진이 얼마나 쉽게 만들어지는지 확인 · 실존 인물·사고 장면 금지 · 1인 2장',
      suggestions: [
        '눈 덮인 사막 위에 착륙한 여객기, 뉴스 사진 스타일',
        '바닷속을 나는 비행기와 물고기 떼, 사실적인 사진',
        '학교 운동장에 착륙한 거대한 열기구, 휴대폰으로 찍은 사진 느낌',
        '무지개색으로 도색된 여객기 광고 사진, 공항 활주로 배경',
        '달 표면 활주로에 서 있는 여객기, 사실적인 사진',
      ],
    },
    'roleplay-investigation': {
      type: 'roleplay',
      id: 'roleplay-investigation',
      title: 'AI 사고 조사위원회',
      intro: '가상 사례 · 조사위원이 되어 정비사에게 질문 → 문제의 근본 원인 찾기',
      systemPrompt:
        '너는 가상의 항공 정비 회사 "한빛에어텍"의 3년차 정비사 김민수 역할이다. 이 이야기는 교육용 가상 사례다. 상황: 소형 훈련기 정비 중 AI 챗봇에게 바퀴 고정 볼트의 조임 토크 값을 물었고, 챗봇이 그럴듯한 숫자를 답해서 정비 매뉴얼을 확인하지 않고 그 값으로 작업했다. 이후 다음 점검에서 볼트가 규정보다 약하게 조여진 것이 발견됐고 다행히 사고는 없었다. 학생은 사고 조사위원이다. 한국어로 짧게 2~4문장으로, 긴장하지만 솔직한 목소리로 답해. 처음에는 "AI가 알려준 값이었어요"라며 AI 탓을 하다가, 학생이 매뉴얼 확인·교차 검증·절차에 대해 구체적으로 물으면 그때 "사실 정비 매뉴얼로 검증 절차를 거치지 않았습니다. 원인은 검증 절차 누락입니다"라고 인정해. 학생이 그 방향으로 묻기 전에는 "검증 절차 누락"이라는 말을 절대 먼저 하지 마. 실제 항공기 기종·실존 회사·실제 토크 수치는 언급하지 마. 부적절한 요청은 정중히 거절해.',
      missionKeyword: '검증 절차 누락',
      missionDescription:
        '정비사에게 질문해 이 사건의 근본 원인을 정비사 입으로 인정하게 만들기. 힌트: AI가 틀린 것만이 원인일까? 작업 전에 무엇을 확인했어야 할까?',
    },
    'vibe-lv2': {
      type: 'vibe',
      id: 'vibe-lv2',
      title: '바이브코딩 Lv.2 — AI가 만든 앱 검증하기',
      intro: '1교시에 만든 내 앱 불러오기 → 틀린 정보·버그 찾기 → 검증 기능 추가',
      task:
        '1교시에 만든 앱을 AI에게 점검시키기. ① "이 앱에서 틀린 정보나 버그 찾아서 알려줘" ② 찾은 문제 하나씩 수정 요청 ③ 검증 기능 추가 — 예: 정보마다 출처 표시, "매뉴얼 확인함" 체크 칸, 입력값이 이상하면 경고. 1교시 앱이 없으면 새로 만들어도 됨.',
      ideas: [
        '이 앱에서 틀린 정보나 버그를 찾아서 목록으로 알려줘',
        '모든 수치 옆에 "정비 매뉴얼로 확인 필요" 안내 문구 추가해줘',
        '항목마다 "매뉴얼 확인함" 체크 칸을 추가해줘',
        '입력값이 0보다 작거나 너무 크면 빨간색 경고를 띄워줘',
        '화면 아래에 "이 앱은 학습용이며 실제 정비에는 사용 금지" 문구 추가해줘',
      ],
      continueMode: 'continue',
      maxBuilds: 6,
    },
    'quiz-ethics': {
      type: 'quiz',
      id: 'quiz-ethics',
      title: 'AI 윤리 상황 판단 퀴즈',
      intro: '가장 바람직한 행동 고르기 · 문항마다 해설 확인',
      questions: [
        {
          id: 'e1',
          question: '친구 얼굴 사진으로 AI 합성 영상을 만들어 단톡방에 장난으로 올리려 한다. 가장 알맞은 판단은?',
          options: [
            '장난이니 괜찮다',
            '친구가 모르면 괜찮다',
            '동의 없는 합성은 인격권 침해이자 처벌 대상 가능 → 만들지 않는다',
            '얼굴만 살짝 바꾸면 괜찮다',
          ],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: '타인 동의 없는 딥페이크 = 인격권 침해 · 내용에 따라 형사 처벌 대상 · 장난이라는 의도와 무관',
        },
        {
          id: 'e2',
          question: 'AI로 만든 이미지를 동아리 포스터에 쓰려 한다. 가장 바람직한 방법은?',
          options: [
            '특정 작가 화풍을 그대로 흉내 내라고 요청한다',
            '서비스 이용 약관을 확인하고 AI 생성 이미지임을 표시한다',
            '유명 캐릭터를 그대로 그려 달라고 한다',
            '출처 없이 내가 그렸다고 한다',
          ],
          correctIndex: 1,
          timeLimitSec: 20,
          explanation: '저작권·상표 침해 소지 회피 · 이용 약관 확인 · AI 생성 사실 표시가 정직한 사용',
        },
        {
          id: 'e3',
          question: '실습 기록을 정리하려고 반 친구들의 이름·전화번호 명단을 AI 챗봇에 붙여 넣으려 한다?',
          options: [
            '편하니까 그대로 넣는다',
            '개인정보는 지우거나 가린 뒤 넣는다',
            '전화번호만 넣는다',
            '친구 몰래 넣으면 된다',
          ],
          correctIndex: 1,
          timeLimitSec: 20,
          explanation: '입력한 정보의 저장·학습 여부 불확실 · 타인 개인정보는 삭제·가명 처리 후 사용',
        },
        {
          id: 'e4',
          question: 'AI가 추천한 정비 절차대로 작업했는데 문제가 생겼다. 책임은 누구에게 있을까?',
          options: [
            'AI에게만 있다',
            'AI를 만든 회사에게만 있다',
            '결과를 확인하고 작업을 결정한 사람에게 있다',
            '아무에게도 없다',
          ],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: 'AI = 도구 · 최종 판단과 서명은 사람의 몫 · 항공 정비에서는 확인하고 서명한 정비사가 책임',
        },
        {
          id: 'e5',
          question: '동료가 AI 결과를 확인하지 않은 실수를 스스로 보고했다. 항공 안전 문화(Just Culture)에 맞는 대응은?',
          options: [
            '무조건 징계해서 본보기로 삼는다',
            '실수를 숨기도록 한다',
            '보고를 존중하고 원인을 분석해 절차를 개선한다',
            '못 들은 척한다',
          ],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: 'Just Culture · 정직한 실수 보고는 처벌보다 학습 대상 · 단, 고의·중대한 부주의는 책임 추궁',
        },
      ],
    },

    // ── 3교시. AI 시대 항공 진로 ──
    'poll-aviation-ai': {
      type: 'poll',
      id: 'poll-aviation-ai',
      title: '가장 기대되는 항공 AI 분야',
      prompt: '10년 뒤 가장 기대되는 항공 AI 분야는?',
      mode: 'choice',
      options: [
        '예측 정비(PHM)',
        '드론 · UAM(도심항공교통)',
        '비전 AI 외관 검사',
        'AI 항공 관제 지원',
        '디지털 트윈 · VR 정비 훈련',
        '자율 비행',
      ],
    },
    'poll-new-jobs': {
      type: 'poll',
      id: 'poll-new-jobs',
      title: '새로 생길 항공 일자리',
      prompt: 'AI 때문에 새로 생길 것 같은 항공 일자리 한 단어',
      mode: 'wordcloud',
      anonymous: true,
    },
    'image-future-me': {
      type: 'image',
      id: 'image-future-me',
      maxImages: 2,
      title: '10년 뒤 항공 현장의 나',
      intro: '10년 뒤 일하는 모습을 묘사 → 이미지 생성 · 3교시 포트폴리오 앱에 사용 · 1인 2장',
      suggestions: [
        '태블릿으로 AI 진단 결과를 보며 여객기 엔진을 점검하는 정비사, 격납고, 사실적인 사진',
        '드론 여러 대를 관제 화면으로 운영하는 드론 운용 전문가, 미래형 통제실, 일러스트',
        'AR 안경을 쓰고 항공기 날개를 검사하는 기술자, 밝은 조명, 3D 렌더링',
        '도심항공교통(UAM) 버티포트에서 기체를 점검하는 정비사, 해 질 녘, 디지털 아트',
      ],
    },
    'tutor-career': {
      type: 'tutor',
      id: 'tutor-career',
      title: 'AI 진로 코치 — 나의 항공 AI 로드맵',
      intro: '관심 분야와 현재 상황 입력 → 고등학교 · 졸업 후 · 5년 뒤 단계별 로드맵 코칭',
      subject: 'general',
      taskDescription:
        '항공 특성화고 학생의 진로 로드맵 코칭. 입력 예: "항공정비과 2학년, 드론에 관심, 코딩은 처음" → 고등학교 재학 중 준비할 것(자격증·실습·동아리), 졸업 후 경로(취업·진학·군 기술병 등 선택지), 5년 뒤 목표 역할과 필요한 AI 역량을 단계별로 제시. 특정 학교·기업 이름이나 합격 보장 같은 단정은 피하고, 사실이 불확실한 정보는 확인이 필요하다고 표시. 마지막에 포트폴리오 앱에 넣을 한 줄 목표 문장 제안.',
    },
    'vibe-lv3': {
      type: 'vibe',
      id: 'vibe-lv3',
      title: '바이브코딩 Lv.3 — 나의 진로 포트폴리오',
      intro: '지금까지 만든 앱 + 내 이미지 + 진로 로드맵 → 한 페이지 포트폴리오 완성',
      task:
        '내 진로 포트폴리오 페이지 완성하기. ① 맨 위: 10년 뒤 나의 모습 이미지와 한 줄 목표 ② 가운데: AI 코치와 만든 단계별 로드맵(고등학교 · 졸업 후 · 5년 뒤) ③ 아래: 1·2교시에 만든 앱 기능 연결 또는 소개. 실명·전화번호 등 개인정보는 넣지 않기.',
      ideas: [
        '내가 만든 이미지를 맨 위에 크게 넣고 한 줄 목표를 적어줘',
        '고등학교, 졸업 후, 5년 뒤 3단계 로드맵을 타임라인으로 보여줘',
        '1교시에 만든 앱을 아래쪽에 그대로 넣어줘',
        '항공기 느낌이 나게 하늘색과 흰색 디자인으로 바꿔줘',
        '관심 분야 태그(드론, 예측 정비 등)를 버튼으로 보여줘',
      ],
      continueMode: 'continue',
      useMyImages: true,
      maxBuilds: 8,
    },
    'poll-showcase': {
      type: 'poll',
      id: 'poll-showcase',
      title: '작품 자랑 투표',
      prompt: '오늘 가장 마음에 든 나의 결과물은?',
      mode: 'choice',
      options: ['미래 항공기 이미지', 'Lv.1 첫 항공 앱', 'Lv.2 검증 기능', '10년 뒤 나의 이미지', 'Lv.3 진로 포트폴리오'],
    },
    'quiz-final': {
      type: 'quiz',
      id: 'quiz-final',
      title: '종합 퀴즈 대회',
      intro: '3교시 전체 총정리 · 빠르고 정확할수록 고득점',
      autoReveal: true,
      questions: [
        {
          id: 'f1',
          question: '생성형 AI가 글을 만드는 핵심 원리는?',
          options: ['실시간 인터넷 검색', '다음에 올 말을 확률로 예측', '정답표 복사', '무작위 추첨'],
          correctIndex: 1,
          timeLimitSec: 15,
        },
        {
          id: 'f2',
          question: '말로 설명해서 AI가 코드를 쓰게 하는 개발 방식은?',
          options: ['블록 코딩', '바이브코딩', '하드 코딩', '어셈블리'],
          correctIndex: 1,
          timeLimitSec: 15,
        },
        {
          id: 'f3',
          question: '바이브코딩에서 앱을 고칠 때 좋은 요청 방법은?',
          options: ['모든 수정을 한 번에 길게', '한 번에 하나씩 구체적으로', '"알아서 잘"이라고만', '처음부터 매번 새로'],
          correctIndex: 1,
          timeLimitSec: 15,
        },
        {
          id: 'f4',
          question: 'AI가 알려준 정비 수치를 쓰기 전에 할 일은?',
          options: ['바로 작업', '친구에게 물어보기', '승인된 정비 매뉴얼로 확인', 'AI에게 한 번 더 묻기만'],
          correctIndex: 2,
          timeLimitSec: 15,
        },
        {
          id: 'f5',
          question: '타인 동의 없는 딥페이크 제작은?',
          options: ['재미있는 장난', '인격권 침해 · 처벌 대상 가능', '권장 활동', '문제없음'],
          correctIndex: 1,
          timeLimitSec: 15,
        },
        {
          id: 'f6',
          question: '정직한 실수 보고를 처벌보다 학습의 기회로 삼는 항공 안전 문화는?',
          options: ['Just Culture', 'Fast Culture', 'Blame Culture', 'Pop Culture'],
          correctIndex: 0,
          timeLimitSec: 15,
        },
        {
          id: 'f7',
          question: '센서 데이터로 부품 고장 시점을 미리 예측해 정비하는 방식은?',
          options: ['사후 정비', '예측 정비(PHM)', '임시 정비', '외주 정비'],
          correctIndex: 1,
          timeLimitSec: 15,
        },
      ],
    },

    // ── 마무리 ──
    'poll-feedback': {
      type: 'poll',
      id: 'poll-feedback',
      title: '소감 한마디',
      prompt: '오늘 특강을 한 단어로 남긴다면?',
      mode: 'wordcloud',
      anonymous: true,
    },
  },
  slides: buildSlides(),
};

function buildSlides(): Slide[] {
  const P0 = '입장 · 워밍업';
  const P1 = '1교시 · 생성형 AI와 바이브코딩';
  const P2 = '2교시 · AI 윤리';
  const P3 = '3교시 · AI 시대 항공 진로';
  const P4 = '마무리';
  const S = (s: Slide) => s;
  return [
    // ── 파트 0 · 입장·워밍업 (0:00–0:08) ──
    S({ id: 'g0-1', part: 0, partTitle: P0, layout: 'title',
      title: '경남항공고 AI 특강',
      subtitle: '바이브코딩 · AI 윤리 · 항공 AI 진로 | 50분 × 3교시',
      blocks: [
        { kind: 'p', text: '일시 : 확정 후 기입 · 장소 : 확정 후 기입' },
        { kind: 'p', text: '대상 : 경남항공고등학교 학생' },
        { kind: 'p', text: '강사 조성호 · 부산대학교 AI융합교육원 강사 / KODE KOREA(코드코리아) 대표' },
      ],
      notes: '입장 시간. 화면 QR·방 코드 안내 반복. 300명 입장 확인 후 시작. 와이파이 불안정 시 LTE 사용 안내. 닉네임은 실명 대신 별명 권장(개인정보 수칙 예고).' }),
    S({ id: 'g0-2', part: 0, partTitle: P0, layout: 'content',
      title: 'Contents',
      blocks: [
        { kind: 'bullet', text: '00 · 0:00–0:08 · 입장 · 워밍업 — 워드클라우드 · OX 퀴즈' },
        { kind: 'bullet', text: '01 · 0:08–0:50 · 생성형 AI와 바이브코딩 — 이미지 생성 · 첫 앱 제작' },
        { kind: 'note', text: '휴식 10분' },
        { kind: 'bullet', text: '02 · 1:00–1:50 · AI 윤리 — 환각 · 가짜 사진 · 사고 조사 역할극 · 앱 검증' },
        { kind: 'note', text: '휴식 10분' },
        { kind: 'bullet', text: '03 · 2:00–2:50 · AI 시대 항공 진로 — 항공 AI 현장 · 진로 로드맵 · 포트폴리오 완성' },
      ],
      notes: '30초. 흐름만. 바이브코딩 앱 하나를 3교시 내내 키운다는 점 강조.' }),
    S({ id: 'g0-3', part: 0, partTitle: P0, layout: 'big',
      title: '들어가기 전에…',
      subtitle: '코딩을 배운 적 없는 사람도 오늘 앱을 만들 수 있을까?',
      notes: '답 받지 않고 던지기만. 1교시 끝에 각자 폰의 앱으로 답 확인.' }),
    S({ id: 'g0-4', part: 0, partTitle: P0, layout: 'content',
      title: '학습 목표',
      blocks: [
        { kind: 'h', text: '목표 1 · 이해' },
        { kind: 'bullet', text: '생성형 AI의 작동 원리와 한계(환각) 이해' },
        { kind: 'bullet', text: 'AI 사용 시 책임 · 저작권 · 개인정보 · 딥페이크 쟁점 판단' },
        { kind: 'h', text: '목표 2 · 제작' },
        { kind: 'bullet', text: '바이브코딩으로 항공 앱 제작 → 검증 → 개선' },
        { kind: 'bullet', text: '항공 AI 분야 탐색과 나의 진로 로드맵 작성' },
        { kind: 'callout', text: '최종 결과물 : 스마트폰에서 열리는 나의 진로 포트폴리오 앱' },
      ],
      notes: '1분. 목표 2의 결과물이 3교시 끝의 포트폴리오라는 점만 짚기.' }),
    S({ id: 'g0-5', part: 0, partTitle: P0, layout: 'big',
      title: 'AI 하면 떠오르는 단어는?',
      subtitle: '스마트폰으로 한 단어 입력',
      activityId: 'poll-warmup',
      notes: '2분. 익명 워드클라우드. 큰 단어 2~3개 읽어 주며 반응 유도. "챗GPT"가 크면 다음 퀴즈로 연결.' }),
    S({ id: 'g0-6', part: 0, partTitle: P0, layout: 'big',
      title: '몸풀기 OX 퀴즈',
      subtitle: '3문항 · 빠를수록 고득점 · 점수는 3교시 끝까지 누적',
      activityId: 'quiz-warmup',
      notes: '3분. 점수·리더보드 작동 확인용. 문항별 해설은 한 줄로만. 3번 문항 정답 공개 후 "1교시에 직접 확인" 예고.' }),

    // ── 파트 1 · 1교시 (0:08–0:50) ──
    S({ id: 'g1-1', part: 1, partTitle: P1, layout: 'section',
      title: '01 · 1교시',
      subtitle: '0:08 – 0:50 · 생성형 AI와 바이브코딩' }),
    S({ id: 'g1-2', part: 1, partTitle: P1, layout: 'content',
      title: '생성형 AI = 다음에 올 말을 예측하는 모델',
      blocks: [
        { kind: 'p', text: '1-1 · 개념' },
        { kind: 'bullet', text: '방대한 글 · 이미지 · 코드 학습 → 가장 그럴듯한 다음 조각을 하나씩 생성' },
        { kind: 'bullet', text: '"오늘 날씨가 ___" → "맑다" · "좋다" 확률 예측의 반복' },
        { kind: 'bullet', text: '생성 대상 : 글 · 이미지 · 음성 · 영상 · 코드' },
        { kind: 'callout', text: '핵심 : 검색이 아닌 생성 → 그럴듯함과 정확함은 별개' },
      ],
      notes: '3분. 워밍업 1번 문항과 연결. "정확함은 별개"는 2교시 환각 복선.' }),
    S({ id: 'g1-3', part: 1, partTitle: P1, layout: 'twocol',
      title: '잘하는 것 · 못하는 것',
      blocks: [
        { kind: 'h', text: '잘하는 것' },
        { kind: 'bullet', text: '초안 · 아이디어 빠른 생성' },
        { kind: 'bullet', text: '요약 · 번역 · 코드 작성' },
        { kind: 'bullet', text: '지치지 않는 반복 수정' },
        { kind: 'h', text: '못하는 것' },
        { kind: 'bullet', text: '최신 · 정확한 사실 보장' },
        { kind: 'bullet', text: '결과에 대한 책임' },
        { kind: 'bullet', text: '환각 — 그럴듯한 거짓 답' },
      ],
      notes: '2분. 오른쪽 열은 2교시에서 다시 다룬다고만 언급.' }),
    S({ id: 'g1-4', part: 1, partTitle: P1, layout: 'content',
      title: '이미지 생성 요청 = 장면 + 분위기 + 스타일',
      blocks: [
        { kind: 'p', text: '1-2 · 이미지 생성' },
        { kind: 'bullet', text: '장면 : 무엇이 · 어디서 · 무엇을 (예: 도심 빌딩 사이를 나는 UAM)' },
        { kind: 'bullet', text: '분위기 : 시간대 · 날씨 · 조명 (예: 해 질 녘, 밝은 조명)' },
        { kind: 'bullet', text: '스타일 : 사진 · 수채화 · 3D 렌더링 · 디지털 아트' },
        { kind: 'callout', text: '원칙 : 구체적 묘사 → 원하는 결과에 근접' },
      ],
      notes: '1분. 예시 칩 그대로 눌러도 된다고 안내 후 바로 실습.' }),
    S({ id: 'g1-5', part: 1, partTitle: P1, layout: 'big',
      title: '2040년 미래 항공기 그리기',
      subtitle: '장면 · 분위기 · 스타일을 넣어 묘사 · 1인 2장',
      activityId: 'image-future-aircraft',
      notes: '6분. 이미지 크레딧 제한 → 1인 약 2장 안내 필수. 생성 10~20초 소요, 연타 금지 안내. 잘 나온 작품 2~3개를 학생 폰으로 받아 구두 소개.' }),
    S({ id: 'g1-6', part: 1, partTitle: P1, layout: 'content',
      title: '바이브코딩(Vibe Coding)',
      blocks: [
        { kind: 'p', text: '1-3 · 바이브코딩' },
        { kind: 'bullet', text: '원하는 기능을 말로 설명 → AI가 코드 작성 → 실행 결과 확인 → 말로 수정' },
        { kind: 'bullet', text: '2025년 AI 연구자 안드레이 카파시(Andrej Karpathy)가 처음 쓴 표현' },
        { kind: 'bullet', text: '코드 문법 암기보다 원하는 결과를 정확히 설명하는 능력이 중요' },
        { kind: 'callout', text: '비유 : 챗봇 = 창밖에서 레시피 불러주는 사람 · 바이브코딩 = 주방에 들어와 요리하는 사람에게 맡기기' },
      ],
      notes: '2분. 들어가기 전 질문 다시 꺼내기. 오늘 만든 앱은 폰 브라우저에서 바로 실행.' }),
    S({ id: 'g1-7', part: 1, partTitle: P1, layout: 'content',
      title: '좋은 요청 공식 = 누가 + 무엇을 + 어떻게 보이게',
      blocks: [
        { kind: 'p', text: '1-4 · 요청 공식' },
        { kind: 'bullet', text: '누가 : 항공정비과 학생이 실습 중에' },
        { kind: 'bullet', text: '무엇을 : 외부 점검 항목 10개를 체크하고 진행률 확인' },
        { kind: 'bullet', text: '어떻게 보이게 : 큰 체크 버튼 · 하늘색 배경 · 완료 시 축하 문구' },
        { kind: 'quote', text: '> 항공정비과 학생이 실습 중에 쓸 외부 점검 체크리스트 앱 만들어줘. 항목 10개를 체크하면 진행률이 보이고, 버튼은 크게, 하늘색 배경으로.' },
        { kind: 'callout', text: '수정 원칙 : 한 번에 하나씩 · 구체적으로' },
      ],
      notes: '2분. 나쁜 예 "앱 만들어줘"와 비교해서 말로만 설명. 수정도 "버튼 색 바꿔줘"처럼 하나씩.' }),
    S({ id: 'g1-8', part: 1, partTitle: P1, layout: 'content',
      title: '시연 흐름',
      blocks: [
        { kind: 'p', text: '1-5 · 시연' },
        { kind: 'bullet', text: '① 아이디어 칩 선택 또는 요청 입력' },
        { kind: 'bullet', text: '② 생성 대기 (코드 작성 과정 표시)' },
        { kind: 'bullet', text: '③ 앱 실행 · 직접 눌러 보기' },
        { kind: 'bullet', text: '④ 마음에 안 드는 점 하나 → 수정 요청 → 다시 확인' },
        { kind: 'callout', text: '생성 · 수정 횟수 제한 : 1인 6회 → 요청 전에 한 번 더 생각' },
      ],
      notes: '3분. 강사 폰(또는 강사 계정 학생 화면) 프로젝터 미러링으로 체크리스트 앱 실시연. 생성 시간 20~60초, 대기 중 요청 공식 다시 짚기.' }),
    S({ id: 'g1-9', part: 1, partTitle: P1, layout: 'content',
      title: '바이브코딩 안전 수칙',
      blocks: [
        { kind: 'bullet', text: '실명 · 전화번호 · 주소 · 사진 등 개인정보 입력 금지' },
        { kind: 'bullet', text: '앱 속 수치 · 정보 = AI 생성물 → 그대로 믿기 금지' },
        { kind: 'bullet', text: '실제 정비 작업에 사용 금지 · 학습용' },
        { kind: 'bullet', text: '다른 사람을 비방 · 조롱하는 앱 금지' },
        { kind: 'callout', text: '원칙 : 만든 사람 = 확인할 책임이 있는 사람' },
      ],
      notes: '1분. 2교시 윤리 파트 예고. 부적절 요청은 자동 차단된다는 점도 안내.' }),
    S({ id: 'g1-10', part: 1, partTitle: P1, layout: 'big',
      title: '연습 단계 1 · 18분 — 나의 첫 항공 앱',
      subtitle: '바이브코딩 Lv.1',
      activityId: 'vibe-lv1',
      blocks: [
        { kind: 'bullet', text: '1. 아이디어 선택 또는 직접 구상 (누가 · 무엇을 · 어떻게 보이게)' },
        { kind: 'bullet', text: '2. 요청 입력 → 앱 생성 → 직접 실행' },
        { kind: 'bullet', text: '3. 수정 요청 2회 이상 (한 번에 하나씩)' },
        { kind: 'callout', text: '합격 조건 : 폰에서 동작하는 앱 1개 + 수정 2회' },
        { kind: 'note', text: '확인 포인트 : 버튼 · 입력이 실제로 동작하는지 · 진행 : 12분 경과 시 마무리 안내' },
      ],
      notes: '18분. 300명 동시 생성 → 대기 시간 길어질 수 있음, 연타 금지 안내. 막힌 학생은 아이디어 칩 사용. 앱은 자동 저장, 2교시에 이어서 사용. 10분 지점에 잘 만든 앱 2~3개 구두 소개.' }),
    S({ id: 'g1-11', part: 1, partTitle: P1, layout: 'content',
      title: '01 정리',
      blocks: [
        { kind: 'bullet', text: '생성형 AI = 다음 조각 예측 · 그럴듯함 ≠ 정확함' },
        { kind: 'bullet', text: '이미지 요청 = 장면 + 분위기 + 스타일' },
        { kind: 'bullet', text: '바이브코딩 = 말로 설명 → 생성 → 확인 → 하나씩 수정' },
        { kind: 'note', text: '휴식 10분 · 1:00 시작 · 다음 02 · AI 윤리' },
      ],
      notes: '2분. 앱 저장됨 안내. 쉬는 시간에도 입장 상태 유지(페이지 닫아도 재입장 가능).' }),
    S({ id: 'g1-12', part: 1, partTitle: P1, layout: 'big',
      title: '쉬는 시간 10분',
      subtitle: '1:00 시작 · 다음 02 · AI 윤리 — 내 앱, 믿어도 될까?',
      notes: '타이머 표시. 폰 배터리 확인 안내.' }),

    // ── 파트 2 · 2교시 (1:00–1:50) ──
    S({ id: 'g2-1', part: 2, partTitle: P2, layout: 'section',
      title: '02 · 2교시',
      subtitle: '1:00 – 1:50 · AI 윤리' }),
    S({ id: 'g2-2', part: 2, partTitle: P2, layout: 'big',
      title: '1교시에 만든 앱에서 틀린 정보가 나온다면, 책임은 누구에게?',
      subtitle: 'AI · 앱을 만든 나 · 앱을 쓴 사람',
      notes: '3분. 손들기 또는 구두 반응만. 정답 공개 없이 2교시 끝 퀴즈 4번에서 회수.' }),
    S({ id: 'g2-3', part: 2, partTitle: P2, layout: 'content',
      title: '환각(Hallucination)',
      blocks: [
        { kind: 'p', text: '2-1 · 환각' },
        { kind: 'bullet', text: '정의 : 사실이 아닌 내용을 사실처럼 생성하는 현상' },
        { kind: 'bullet', text: '원인 : 정답 검색이 아닌 그럴듯한 다음 말 예측' },
        { kind: 'bullet', text: '특징 : 틀린 답도 자신 있는 말투 → 겉보기로 구분 불가' },
        { kind: 'bullet', text: '항공 현장 위험 : 존재하지 않는 부품 번호 · 토크 값 · 절차 생성 가능' },
        { kind: 'callout', text: '기준 : 정비 수치 · 절차의 근거 = 승인된 정비 매뉴얼' },
      ],
      notes: '3분. 실제 매뉴얼 수치 예시는 들지 말 것(가상 수치도 오해 소지). 법률 분야에서 AI가 지어낸 판례가 제출돼 문제가 된 해외 사례가 있었다는 정도만 언급 가능.' }),
    S({ id: 'g2-4', part: 2, partTitle: P2, layout: 'big',
      title: '환각 OX — 정비 매뉴얼 수치',
      subtitle: '그럴듯한 AI 답, 바로 써도 될까?',
      activityId: 'ox-hallucination',
      notes: '2분. 정답 X. 해설 후 "그럴듯함 ≠ 정확함" 한 번 더.' }),
    S({ id: 'g2-5', part: 2, partTitle: P2, layout: 'content',
      title: '가짜 사진 · 딥페이크',
      blocks: [
        { kind: 'p', text: '2-2 · 딥페이크' },
        { kind: 'bullet', text: '딥페이크(Deepfake) : AI로 실제처럼 합성한 이미지 · 영상 · 음성' },
        { kind: 'bullet', text: '문장 몇 줄 → 사진처럼 보이는 가짜 이미지 생성 가능' },
        { kind: 'bullet', text: '타인 얼굴 · 목소리 무단 합성 = 인격권 침해 · 처벌 대상 가능' },
        { kind: 'callout', text: '원칙 : 실존 인물 · 실제 사고 장면 생성 금지' },
      ],
      notes: '2분. 실습 전에 금지 원칙부터 못박기. 안전 필터가 걸러 내지만 필터 우회 시도 금지 안내.' }),
    S({ id: 'g2-6', part: 2, partTitle: P2, layout: 'big',
      title: '진짜일까 가짜일까',
      subtitle: '실제로 없는 장면을 사진처럼 만들기 · 1인 2장',
      activityId: 'image-real-or-fake',
      notes: '6분. 가장 진짜 같은 작품 2~3개를 구두로 소개하며 "뉴스에 이 사진이 나오면 믿을까?" 질문. 이미지 크레딧 제한 재안내.' }),
    S({ id: 'g2-7', part: 2, partTitle: P2, layout: 'content',
      title: 'AI 사용의 4가지 쟁점',
      blocks: [
        { kind: 'p', text: '2-3 · 쟁점' },
        { kind: 'bullet', text: '책임 : 최종 판단과 서명 = 사람' },
        { kind: 'bullet', text: '저작권 : 작가 화풍 · 캐릭터 무단 모방 주의 · AI 생성 사실 표시' },
        { kind: 'bullet', text: '개인정보 : 이름 · 연락처 · 얼굴 사진 입력 금지 · 가명 처리' },
        { kind: 'bullet', text: '검증 : 중요한 정보 = 공식 자료로 교차 확인' },
      ],
      notes: '3분. 각 쟁점을 이어질 퀴즈 문항과 연결해 예고만.' }),
    S({ id: 'g2-8', part: 2, partTitle: P2, layout: 'content',
      title: '항공 안전 문화 = Just Culture',
      blocks: [
        { kind: 'bullet', text: '정직한 실수 보고 → 처벌보다 원인 분석 · 절차 개선' },
        { kind: 'bullet', text: '고의 위반 · 중대한 부주의 → 책임 추궁' },
        { kind: 'bullet', text: '목적 : 숨겨진 실수 → 반복되는 사고 방지' },
        { kind: 'callout', text: '적용 : AI 결과를 검증하지 않은 실수도 보고 · 공유 대상' },
      ],
      notes: '2분. 항공 분야가 보고 문화를 중시하는 이유 설명. 다음 역할극 도입.' }),
    S({ id: 'g2-9', part: 2, partTitle: P2, layout: 'big',
      title: '연습 단계 2 · 10분 — AI 사고 조사위원회',
      subtitle: '가상 사례 · 조사위원이 되어 근본 원인 찾기',
      activityId: 'roleplay-investigation',
      blocks: [
        { kind: 'bullet', text: '상황 : 정비사가 AI 챗봇이 알려준 토크 값으로 작업 → 다음 점검에서 조임 부족 발견' },
        { kind: 'bullet', text: '1. 무슨 일이 있었는지 질문' },
        { kind: 'bullet', text: '2. 작업 전 확인 절차 질문' },
        { kind: 'callout', text: '합격 조건 : 정비사가 근본 원인을 직접 인정 → 미션 클리어 보너스 점수' },
        { kind: 'note', text: '진행 : 5분 경과 시 힌트 — "매뉴얼로 확인했나요?"' },
      ],
      notes: '10분. 가상 사례임을 명확히. 미션 클리어 학생 수 확인, 클리어한 학생 질문 1~2개 구두 공유. 결론: 원인은 AI 오류가 아닌 검증 절차 누락.' }),
    S({ id: 'g2-10', part: 2, partTitle: P2, layout: 'big',
      title: '연습 단계 3 · 12분 — 내 앱 검증하기',
      subtitle: '바이브코딩 Lv.2 · 1교시 앱 불러오기',
      activityId: 'vibe-lv2',
      blocks: [
        { kind: 'bullet', text: '1. "틀린 정보나 버그 찾아줘" 요청' },
        { kind: 'bullet', text: '2. 찾은 문제 하나씩 수정' },
        { kind: 'bullet', text: '3. 검증 기능 추가 : 출처 표시 · 확인 체크 칸 · 입력값 경고' },
        { kind: 'callout', text: '합격 조건 : 수정 1회 이상 + 검증 기능 1개 추가' },
        { kind: 'note', text: '확인 포인트 : AI가 찾은 버그가 진짜 버그인지 직접 눌러 확인' },
      ],
      notes: '12분. 1교시 앱이 자동으로 불러와짐. 앱이 없는 학생은 새로 만들기. AI가 버그 목록도 틀릴 수 있다는 점 강조 = 검증의 검증.' }),
    S({ id: 'g2-11', part: 2, partTitle: P2, layout: 'big',
      title: 'AI 윤리 상황 판단 퀴즈',
      subtitle: '5문항 · 가장 바람직한 행동은?',
      activityId: 'quiz-ethics',
      notes: '5분. 문항당 20초 + 해설 30초. 4번 문항에서 2교시 첫 질문(책임은 누구에게?) 회수.' }),
    S({ id: 'g2-12', part: 2, partTitle: P2, layout: 'content',
      title: '02 정리',
      blocks: [
        { kind: 'bullet', text: '환각 → 정비 수치 · 절차는 승인된 매뉴얼로 확인' },
        { kind: 'bullet', text: '딥페이크 · 저작권 · 개인정보 → 동의 · 표시 · 가명 처리' },
        { kind: 'bullet', text: 'AI = 도구 · 책임 = 확인하고 결정한 사람' },
        { kind: 'note', text: '휴식 10분 · 2:00 시작 · 다음 03 · AI 시대 항공 진로' },
      ],
      notes: '1분.' }),
    S({ id: 'g2-13', part: 2, partTitle: P2, layout: 'big',
      title: '쉬는 시간 10분',
      subtitle: '2:00 시작 · 다음 03 · AI 시대 항공 진로 — 10년 뒤 항공 현장의 나',
      notes: '타이머 표시.' }),

    // ── 파트 3 · 3교시 (2:00–2:50) ──
    S({ id: 'g3-1', part: 3, partTitle: P3, layout: 'section',
      title: '03 · 3교시',
      subtitle: '2:00 – 2:50 · AI 시대 항공 진로' }),
    S({ id: 'g3-2', part: 3, partTitle: P3, layout: 'content',
      title: '항공 현장의 AI',
      blocks: [
        { kind: 'p', text: '3-1 · 항공 AI 분야' },
        { kind: 'bullet', text: '예측 정비(PHM) : 센서 데이터 분석 → 고장 전 부품 교체 시점 예측' },
        { kind: 'bullet', text: '비전 AI 외관 검사 : 카메라 · 드론 촬영 → 균열 · 찌그러짐 등 손상 탐지 보조' },
        { kind: 'bullet', text: '드론 · UAM : 자율 비행 · 경로 계획 · 기체 상태 감시' },
        { kind: 'bullet', text: '항공 관제 지원 : 교통 흐름 예측 · 관제사 의사결정 보조' },
        { kind: 'bullet', text: '정비 훈련 : 디지털 트윈 · VR 기반 정비 교육' },
      ],
      notes: '4분. 모두 사람을 "보조"하는 방향임을 강조. 국내외 항공사·제조사들이 예측 정비와 드론 검사를 도입·시험 중이라는 수준으로만 언급, 특정 수치 언급 자제.' }),
    S({ id: 'g3-3', part: 3, partTitle: P3, layout: 'twocol',
      title: '정비사의 일 · 달라지는 부분과 남는 부분',
      blocks: [
        { kind: 'h', text: 'AI가 돕는 부분' },
        { kind: 'bullet', text: '데이터 분석 · 이상 징후 탐지' },
        { kind: 'bullet', text: '반복 촬영 · 1차 외관 검사' },
        { kind: 'bullet', text: '매뉴얼 검색 · 기록 정리' },
        { kind: 'h', text: '사람이 맡는 부분' },
        { kind: 'bullet', text: '최종 판단 · 감항성 확인 · 서명' },
        { kind: 'bullet', text: '실제 수리 · 손기술 · 현장 대응' },
        { kind: 'bullet', text: 'AI 결과 검증 · 안전 책임' },
      ],
      notes: '3분. 2교시 "책임 = 사람"과 연결. AI를 다룰 줄 아는 정비 인력 수요로 연결.' }),
    S({ id: 'g3-4', part: 3, partTitle: P3, layout: 'big',
      title: '10년 뒤 가장 기대되는 항공 AI 분야는?',
      subtitle: '하나 선택',
      activityId: 'poll-aviation-ai',
      notes: '2분. 1위 분야에 대해 한 줄 추가 설명.' }),
    S({ id: 'g3-5', part: 3, partTitle: P3, layout: 'big',
      title: 'AI 때문에 새로 생길 항공 일자리는?',
      subtitle: '한 단어 입력 · 익명',
      activityId: 'poll-new-jobs',
      notes: '3분. 예시 힌트: 드론 운용 · 데이터 정비 · AI 검사 운영. 사라질 일보다 바뀌는 일 관점으로 정리.' }),
    S({ id: 'g3-6', part: 3, partTitle: P3, layout: 'content',
      title: '항공 AI 진로 준비',
      blocks: [
        { kind: 'p', text: '3-2 · 진로' },
        { kind: 'bullet', text: '기본기 : 전공 실습 · 정비 매뉴얼 읽기 · 자격증 준비' },
        { kind: 'bullet', text: 'AI 활용 : 바이브코딩 · 데이터 기초 · 결과 검증 습관' },
        { kind: 'bullet', text: '경험 : 드론 · 코딩 동아리 · 공모전 · 포트폴리오' },
        { kind: 'callout', text: '기준 : 전공 기술 + AI 활용 + 안전 책임감' },
      ],
      notes: '3분. 특정 학교·기업 추천 자제. 자격증 요건 등 세부 사항은 공식 기관 확인 안내.' }),
    S({ id: 'g3-7', part: 3, partTitle: P3, layout: 'big',
      title: '10년 뒤 항공 현장의 나',
      subtitle: '일하는 모습 묘사 → 이미지 생성 · 1인 약 2장 · 포트폴리오에 사용',
      activityId: 'image-future-me',
      notes: '5분. 자기 얼굴 사진·실명 입력 금지 재안내. 이 이미지가 Lv.3 앱에 자동으로 들어갈 수 있다고 안내.' }),
    S({ id: 'g3-8', part: 3, partTitle: P3, layout: 'big',
      title: '연습 단계 4 · 8분 — AI 진로 코치',
      subtitle: '관심 분야 입력 → 단계별 로드맵',
      activityId: 'tutor-career',
      blocks: [
        { kind: 'quote', text: '> 항공정비과 2학년이고 드론에 관심 있어. 코딩은 처음이야. 진로 로드맵 짜줘.' },
        { kind: 'callout', text: '합격 조건 : 고등학교 · 졸업 후 · 5년 뒤 3단계 로드맵 + 한 줄 목표' },
        { kind: 'note', text: '확인 포인트 : AI 추천 중 사실 확인이 필요한 정보 표시' },
      ],
      notes: '8분. 결과 로드맵과 한 줄 목표를 다음 Lv.3 앱에 옮겨 쓰도록 안내(복사해 두기).' }),
    S({ id: 'g3-9', part: 3, partTitle: P3, layout: 'big',
      title: '연습 단계 5 · 13분 — 나의 진로 포트폴리오',
      subtitle: '바이브코딩 Lv.3 · 앱 + 이미지 + 로드맵',
      activityId: 'vibe-lv3',
      blocks: [
        { kind: 'bullet', text: '1. 내 이미지와 한 줄 목표를 맨 위에' },
        { kind: 'bullet', text: '2. 3단계 로드맵을 타임라인으로' },
        { kind: 'bullet', text: '3. 1 · 2교시 앱 연결 또는 소개' },
        { kind: 'callout', text: '합격 조건 : 폰에서 열리는 포트폴리오 1페이지 완성' },
        { kind: 'note', text: '확인 포인트 : 실명 · 연락처 미포함 · 진행 : 10분 경과 시 마무리 안내' },
      ],
      notes: '13분. 이전 앱 자동 불러오기, 생성한 이미지 선택 삽입 가능. 수정 8회까지. 완성 앱 링크는 개인 보관용.' }),
    S({ id: 'g3-10', part: 3, partTitle: P3, layout: 'big',
      title: '작품 자랑 투표',
      subtitle: '오늘 가장 마음에 든 나의 결과물은?',
      activityId: 'poll-showcase',
      notes: '2분. 강사 화면에서 우수작 1~2개 소개(본인 동의 후).' }),
    S({ id: 'g3-11', part: 3, partTitle: P3, layout: 'big',
      title: '종합 퀴즈 대회',
      subtitle: '7문항 · 3교시 전체 총정리 · 누적 점수로 최종 순위',
      activityId: 'quiz-final',
      notes: '4분. 문항당 15초, 자동 정답 공개. 최종 리더보드 상위 3명 발표.' }),
    S({ id: 'g3-12', part: 3, partTitle: P3, layout: 'content',
      title: '03 정리',
      blocks: [
        { kind: 'bullet', text: '항공 AI = 예측 정비 · 비전 검사 · 드론 · UAM · 관제 지원' },
        { kind: 'bullet', text: '사람의 역할 = 최종 판단 · 검증 · 안전 책임' },
        { kind: 'bullet', text: '진로 준비 = 전공 기술 + AI 활용 + 포트폴리오' },
      ],
      notes: '1분.' }),

    // ── 파트 4 · 마무리 ──
    S({ id: 'g4-1', part: 4, partTitle: P4, layout: 'content',
      title: '정리',
      blocks: [
        { kind: 'bullet', text: '이해 : 생성형 AI 원리와 환각 · AI 윤리 쟁점 판단' },
        { kind: 'bullet', text: '제작 : 바이브코딩 앱 제작 → 검증 → 포트폴리오 완성' },
        { kind: 'bullet', text: '진로 : 항공 AI 분야 탐색 · 나의 3단계 로드맵' },
        { kind: 'callout', text: '핵심 : AI가 만들고, 사람이 확인하고, 사람이 책임짐' },
      ],
      notes: '1분. 학습 목표와 1:1 대응 확인.' }),
    S({ id: 'g4-2', part: 4, partTitle: P4, layout: 'big',
      title: '소감 한마디',
      subtitle: '오늘 특강을 한 단어로 · 익명',
      activityId: 'poll-feedback',
      notes: '1분. 워드클라우드 띄운 채로 마무리 인사.' }),
    S({ id: 'g4-3', part: 4, partTitle: P4, layout: 'content',
      title: 'Q&A',
      blocks: [
        { kind: 'h', text: '질문' },
        { kind: 'p', text: 'seongho.cho@kodekorea.kr · kodekorea.kr · github.com/shain1912' },
        { kind: 'note', text: '미해결 질문 → 후속 자료로 회신' },
      ],
      notes: '시간 남을 때만. 300명 강당은 구두 질문 2~3개로 제한.' }),
    S({ id: 'g4-4', part: 4, partTitle: P4, layout: 'title',
      title: '특강 종료',
      subtitle: '다음 과제 : 오늘 만든 포트폴리오 앱에 새 기능 하나 추가',
      blocks: [
        { kind: 'p', text: '강사 조성호 · KODE KOREA(코드코리아) · seongho.cho@kodekorea.kr' },
      ],
      notes: '앱 링크는 강의실 종료 후에도 열람 가능 여부 확인 후 안내.' }),
  ];
}
