import type { Deck, Slide } from '../../../shared/types';

// ──────────────────────────────────────────────────────────────
//  경남항공고 AI 특강 덱 — 항공 특성화고 학생 300명(강당, 스마트폰 참여)
//  50분 × 3교시: 1교시 AI의 이해·현장 지식·바이브코딩 / 2교시 AI 윤리 / 3교시 항공 AI 진로
//  이론: 강사 「1.AI 개요」(정의·약강 AI·범주·역사) + KEPCO 특강 「프롬프트의 종말」(현장 지식)
//  2교시 수치·사례 출처는 슬라이드 note 블록과 강사 노트에 표기 (2026-09 조사)
//  바이브코딩은 교시마다 같은 앱을 이어서 키움 (Lv.1 new → Lv.2·Lv.3 continue)
//  슬라이드 문구는 명사형 개조식, 노트는 "N분." 으로 시작하는 강사 메모 (≤400자 — validate.ts)
//  이미지 슬라이드 파일은 assets/gnaero/ → 시드 시 uploads/ 로 복사
//  레지스트리 미등록 — DB 시드로 탑재
// ──────────────────────────────────────────────────────────────

const IBM_VIDEO = 'https://www.youtube.com/watch?v=k7PvscqGD24';

export const gyeongnamAviation3h: Deck = {
  id: 'gnaero',
  title: '경남항공고 AI 특강 — 바이브코딩 · AI 윤리 · 항공 AI 진로',
  activities: {
    // ── 0. 입장·워밍업 ──
    'poll-warmup': {
      type: 'poll',
      id: 'poll-warmup',
      title: '워밍업 워드클라우드',
      prompt: 'AI 하면 떠오르는 단어 하나',
      mode: 'wordcloud',
      anonymous: true,
    },
    'quiz-warmup': {
      type: 'quiz',
      id: 'quiz-warmup',
      title: '워밍업 OX 퀴즈',
      intro: '몸풀기 3문항 · 빠르고 정확하게',
      questions: [
        {
          id: 'w1',
          question: '생성형 AI가 글을 만드는 기본 원리는 인터넷 글을 찾아서 그대로 복사해 오는 것이다?',
          options: ['O', 'X'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '기본 원리 = 학습한 패턴으로 다음에 올 말을 확률로 예측해 생성 · 검색 기능이 붙은 챗봇도 찾은 자료를 바탕으로 다시 "생성"함',
        },
        {
          id: 'w2',
          question: 'AI는 틀린 내용을 사실처럼 자신 있게 말할 때가 있다?',
          options: ['O', 'X'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '환각(Hallucination) · 그럴듯하지만 사실이 아닌 답 → 사람의 검증 필요',
        },
        {
          id: 'w3',
          question: '코드를 한 줄도 몰라도 말로 설명해서 앱을 만들 수 있다?',
          options: ['O', 'X'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '바이브코딩(Vibe Coding) · 원하는 기능을 말로 설명 → AI가 코드 작성 · 오늘 1교시 실습 내용',
        },
      ],
    },

    // ── 1교시. AI의 이해 · 현장 지식 · 바이브코딩 ──
    'image-future-aircraft': {
      type: 'image',
      id: 'image-future-aircraft',
      maxImages: 3,
      engine: 'svg',
      title: 'AI 그림 코딩 — 2040년 미래 항공기 엠블럼',
      intro: '모양 · 색 · 글자를 말로 설명 → AI가 SVG 코드로 그림 · 1인 3장',
      suggestions: [
        '남색 원 안에 은색 날개와 위로 솟는 전기 수직이착륙기, 아래에 "2040 UAM" 글자',
        '하늘색 배경에 날개와 동체가 하나로 합쳐진 흰색 미래 여객기, 노란 태양',
        '주황색 방패 모양 안에 드론 세 대가 V자로 나는 모습, 굵은 선',
        '밤하늘 배경에 초음속 여객기가 지구 위를 나는 모습, 별 몇 개',
        '초록색 원형 배지, 가운데 프로펠러와 번개 모양, "친환경 비행" 글자',
      ],
    },
    'vibe-lv1': {
      type: 'vibe',
      id: 'vibe-lv1',
      title: '바이브코딩 Lv.1 — 나의 첫 항공 앱',
      intro: '만들고 싶은 앱을 말로 설명 → AI가 폰에서 바로 도는 앱 생성 · 결과 확인 후 한 번에 하나씩 수정',
      task:
        '항공 현장이나 학교생활에 쓸 수 있는 나만의 첫 앱 만들기. 누가 쓰는지 · 무엇을 하는지 · 화면이 어떻게 보이는지 세 가지를 넣어 설명. 완성 후 "버튼 색 바꿔줘"처럼 한 번에 하나씩 수정 요청.',
      ideas: [
        '항공기 외부 점검(Walk-around) 체크리스트 앱 — 항목 체크하면 진행률 표시',
        '토크 단위 변환기 — in-lb, ft-lb, N·m 서로 변환',
        '항공 음성 알파벳(Alpha, Bravo…) 암기 퀴즈 앱',
        '비행기 부품 이름 맞히기 퀴즈 — 점수와 정답 해설 표시',
        '항공 정비 공구 대여 기록장 — 공구 이름과 반납 여부 체크',
        '공항 3글자 코드(ICN, GMP, PUS…) 맞히기 게임',
      ],
      continueMode: 'new',
      maxBuilds: 6,
    },

    // ── 2교시. AI 윤리 ──
    'ox-hallucination': {
      type: 'ox',
      id: 'ox-hallucination',
      title: '환각 OX — 정비 매뉴얼 수치',
      question: 'AI가 알려준 볼트 조임 토크 값이 그럴듯하다. 정비 매뉴얼 확인 없이 바로 작업해도 된다?',
      answer: 'X',
      timeLimitSec: 20,
      explanation: 'AI는 존재하지 않는 수치도 그럴듯하게 생성 가능 · 정비 수치는 반드시 승인된 정비 매뉴얼로 확인',
    },
    'roleplay-investigation': {
      type: 'roleplay',
      id: 'roleplay-investigation',
      title: 'AI 사고 조사위원회',
      intro: '가상 사례 · 조사위원이 되어 정비사에게 질문 → 문제의 근본 원인 찾기',
      systemPrompt:
        '너는 가상의 항공 정비 회사 "한빛에어텍"의 3년차 정비사 김민수 역할이다. 이 이야기는 교육용 가상 사례다. 상황: 소형 훈련기 정비 중 AI 챗봇에게 바퀴 고정 볼트의 조임 토크 값을 물었고, 챗봇이 그럴듯한 숫자를 답해서 정비 매뉴얼을 확인하지 않고 그 값으로 작업했다. 이후 다음 점검에서 볼트가 규정보다 약하게 조여진 것이 발견됐고 다행히 사고는 없었다. 학생은 사고 조사위원이다. 한국어로 짧게 2~4문장으로, 긴장하지만 솔직한 목소리로 답해. 처음에는 "AI가 알려준 값이었어요"라며 AI 탓을 하다가, 학생이 매뉴얼 확인·교차 검증·절차에 대해 구체적으로 물으면 그때 "사실 정비 매뉴얼로 검증 절차를 거치지 않았습니다. 원인은 검증 절차 누락입니다"라고 인정해. 학생이 그 방향으로 묻기 전에는 "검증 절차 누락"이라는 말을 절대 먼저 하지 마. 실제 항공기 기종·실존 회사·실제 토크 수치는 언급하지 마. 부적절한 요청은 정중히 거절해.',
      missionKeyword: '검증 절차 누락',
      missionDescription:
        '정비사에게 질문해 이 사건의 근본 원인을 정비사 입으로 인정하게 만들기. 힌트: AI가 틀린 것만이 원인일까? 작업 전에 무엇을 확인했어야 할까?',
    },
    'vibe-lv2': {
      type: 'vibe',
      id: 'vibe-lv2',
      title: '바이브코딩 Lv.2 — AI가 만든 앱 검증하기',
      intro: '1교시에 만든 내 앱 불러오기 → 틀린 정보·버그 찾기 → 검증 기능 추가',
      task:
        '1교시에 만든 앱을 AI에게 점검시키기. ① "이 앱에서 틀린 정보나 버그 찾아서 알려줘" ② 찾은 문제 하나씩 수정 요청 ③ 검증 기능 추가 — 예: 정보마다 출처 표시, "매뉴얼 확인함" 체크 칸, 입력값이 이상하면 경고. 1교시 앱이 없으면 새로 만들어도 됨.',
      ideas: [
        '이 앱에서 틀린 정보나 버그를 찾아서 목록으로 알려줘',
        '모든 수치 옆에 "정비 매뉴얼로 확인 필요" 안내 문구 추가해줘',
        '항목마다 "매뉴얼 확인함" 체크 칸을 추가해줘',
        '입력값이 0보다 작거나 너무 크면 빨간색 경고를 띄워줘',
        '화면 아래에 "이 앱은 학습용이며 실제 정비에는 사용 금지" 문구 추가해줘',
      ],
      continueMode: 'continue',
      maxBuilds: 6,
    },
    'quiz-ethics2': {
      type: 'quiz',
      id: 'quiz-ethics2',
      title: 'AI 윤리 퀴즈 — 연구와 판례로 보는 위협',
      intro: '2교시에 본 연구 · 판례 · 통계 확인 · 문항마다 해설',
      questions: [
        {
          id: 'e1',
          question: '구글 DeepMind가 실제 생성형 AI 악용 사례 약 200건을 분석했을 때 가장 흔했던 수법은?',
          options: ['AI 서버 해킹', '사람 사칭', '학습 데이터 오염', '로봇 무기화'],
          correctIndex: 1,
          timeLimitSec: 20,
          explanation: '사칭이 20% 이상으로 1위 · 대부분 해킹이 아닌 누구나 쓰는 생성 기능의 악용 (Google DeepMind, 2024)',
        },
        {
          id: 'e2',
          question: '2025년 미국 대학생 설문에서 "AI가 내 진로에 부정적 영향을 줄 것"이라 답한 비율은?',
          options: ['약 15%', '약 35%', '약 55%', '약 85%'],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: '55% · 85%는 과제에 AI를 쓴다고 답한 비율 → 가장 많이 쓰는 세대가 가장 크게 걱정 (Inside Higher Ed, 2025)',
        },
        {
          id: 'e3',
          question: 'IEA가 전망한 2030년 전 세계 데이터센터 전력 소비는 현재 어느 나라의 전체 전력 소비와 비슷할까?',
          options: ['룩셈부르크', '대한민국의 절반', '일본', '전 세계 전체'],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: '약 945TWh ≈ 현재 일본 한 나라 수준 · 2024년 약 415TWh의 두 배 이상 (IEA, 2025)',
        },
        {
          id: 'e4',
          question: '참여도(engagement) 기반 추천 알고리즘이 주로 최대화하려는 것은?',
          options: ['사용자의 학업 성취', '사용자의 수면 시간', '클릭 · 시청 시간', '친구와의 대화 시간'],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: '추천 AI의 지표 = 클릭 · 체류 시간(광고 수익) · 사용자의 행복은 목표에 없음',
        },
        {
          id: 'e5',
          question: '에어캐나다 챗봇이 할인 운임을 잘못 안내한 사건(2024)에서 내려진 판단은?',
          options: ['챗봇은 별개 주체 → 회사 책임 없음', '약관을 안 읽은 고객 책임', '챗봇도 회사의 일부 → 회사 책임', '챗봇 개발사 책임'],
          correctIndex: 2,
          timeLimitSec: 20,
          explanation: '"챗봇은 별개의 법적 주체" 주장 기각 · 자기 웹사이트 챗봇 안내도 회사 책임 (Moffatt v. Air Canada, 2024)',
        },
      ],
    },

    // ── 3교시. AI 시대 항공 진로 ──
    'quiz-two-layers': {
      type: 'quiz',
      id: 'quiz-two-layers',
      title: '일의 두 층 분류 퀴즈',
      intro: '이 일은 AI · 로봇 쪽? 사람 쪽? · 대체 가능성 기준',
      questions: [
        {
          id: 't1',
          question: '격납고 기체 표면을 매일 같은 경로로 촬영해 찌그러짐 · 균열 후보를 표시하는 일',
          options: ['AI · 로봇이 대체할 가능성 큼', '사람이 맡을 가능성 큼'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '반복 층 · 드론 촬영 + 비전 AI 1차 검사 → 후보 판정은 사람이 확인',
        },
        {
          id: 't2',
          question: '점검 결과를 종합해 이 항공기를 오늘 운항에 내보내도 되는지 판단하고 서명하는 일',
          options: ['AI · 로봇이 대체할 가능성 큼', '사람이 맡을 가능성 큼'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '판단 · 책임 층 · 감항성 판단과 최종 확인 · 서명 = 자격을 갖춘 사람의 권한과 책임',
        },
        {
          id: 't3',
          question: '부품 창고의 재고 수량을 세고 입출고를 기록하는 일',
          options: ['AI · 로봇이 대체할 가능성 큼', '사람이 맡을 가능성 큼'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '반복 층 · 바코드 · 센서 · 자동 기록 시스템으로 대체될 가능성 큼',
        },
        {
          id: 't4',
          question: '매뉴얼에 없는 이상 소음의 원인을 찾고 기장 · 운항 담당과 협의해 조치를 결정하는 일',
          options: ['AI · 로봇이 대체할 가능성 큼', '사람이 맡을 가능성 큼'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '판단 · 책임 층 · 예외 상황 대응 + 사람 사이 협의 · 설득 = 사람의 몫 (AI는 자료 검색 보조)',
        },
      ],
    },
    'poll-aviation-ai': {
      type: 'poll',
      id: 'poll-aviation-ai',
      title: '가장 기대되는 항공 AI 분야',
      prompt: '10년 뒤 가장 기대되는 항공 AI 분야는?',
      mode: 'choice',
      options: [
        '예측 정비(PHM)',
        '드론 · UAM(도심항공교통)',
        '비전 AI 외관 검사',
        'AI 항공 관제 지원',
        '디지털 트윈 · VR 정비 훈련',
        '자율 비행',
      ],
    },
    'image-future-me': {
      type: 'image',
      id: 'image-future-me',
      maxImages: 3,
      engine: 'svg',
      title: '나의 항공 진로 윙 배지',
      intro: '10년 뒤 내 직업을 상징하는 배지 디자인 → AI가 SVG 코드로 그림 · 포트폴리오에 사용 · 1인 3장',
      suggestions: [
        '금색 날개 가운데 렌치와 엔진 모양, 아래 리본에 "항공정비사" 글자',
        '파란 원형 배지 안에 드론과 관제 화면, "드론 운용 전문가" 글자',
        '은색 날개 가운데 회로 기판 무늬, "항공전자 엔지니어" 글자',
        '남색 방패 안에 UAM 기체와 도시 실루엣, "UAM 정비사" 글자',
      ],
    },
    'tutor-career': {
      type: 'tutor',
      id: 'tutor-career',
      title: 'AI 진로 코치 — 나의 항공 AI 로드맵',
      intro: '관심 분야와 현재 상황 입력 → 고등학교 · 졸업 후 · 5년 뒤 단계별 로드맵 코칭',
      subject: 'general',
      taskDescription:
        '항공 특성화고 학생의 진로 로드맵 코칭. 관점: 단순 반복 업무는 로봇·AI로 대체될 가능성이 크고, 의사결정과 책임은 사람에게 남음. 입력 예: "항공정비과 2학년, 드론에 관심, 코딩은 처음" → 고등학교(전공 실습·자격증·매뉴얼 읽기), 졸업 후 경로(취업·진학·군 기술병 등 선택지), 5년 뒤 목표 역할을 단계별로 제시하고, 단계마다 판단·책임 역량과 현장 지식, AI 활용 역량을 어떻게 쌓을지 구체적으로 안내. 특정 학교·기업 이름이나 합격 보장 같은 단정은 피하고, 불확실한 정보는 확인 필요로 표시. 마지막에 포트폴리오 앱에 넣을 한 줄 목표 문장 제안.',
    },
    'vibe-lv3': {
      type: 'vibe',
      id: 'vibe-lv3',
      title: '바이브코딩 Lv.3 — 나의 진로 포트폴리오',
      intro: '지금까지 만든 앱 + 내 윙 배지 + 진로 로드맵 → 한 페이지 포트폴리오 완성',
      task:
        '내 진로 포트폴리오 페이지 완성하기. ① 맨 위: 나의 진로 윙 배지와 한 줄 목표 ② 가운데: AI 코치와 만든 단계별 로드맵(고등학교 · 졸업 후 · 5년 뒤) ③ 아래: 1·2교시에 만든 앱 기능 연결 또는 소개. 실명·전화번호 등 개인정보는 넣지 않기.',
      ideas: [
        '내가 만든 윙 배지를 맨 위에 크게 넣고 한 줄 목표를 적어줘',
        '고등학교, 졸업 후, 5년 뒤 3단계 로드맵을 타임라인으로 보여줘',
        '1교시에 만든 앱을 아래쪽에 그대로 넣어줘',
        '항공기 느낌이 나게 하늘색과 흰색 디자인으로 바꿔줘',
        '관심 분야 태그(드론, 예측 정비 등)를 버튼으로 보여줘',
      ],
      continueMode: 'continue',
      useMyImages: true,
      maxBuilds: 8,
    },
    'poll-showcase': {
      type: 'poll',
      id: 'poll-showcase',
      title: '작품 자랑 투표',
      prompt: '오늘 가장 마음에 든 나의 결과물은?',
      mode: 'choice',
      options: ['미래 항공기 엠블럼', 'Lv.1 첫 항공 앱', 'Lv.2 검증 기능', '진로 윙 배지', 'Lv.3 진로 포트폴리오'],
    },
    'quiz-final': {
      type: 'quiz',
      id: 'quiz-final',
      title: '종합 퀴즈 대회',
      intro: '3교시 전체 총정리 · 빠르고 정확할수록 고득점',
      autoReveal: true,
      questions: [
        {
          id: 'f1',
          question: 'AI · 머신러닝 · 딥러닝의 포함 관계로 알맞은 것은?',
          options: ['AI ⊃ 머신러닝 ⊃ 딥러닝', '딥러닝 ⊃ 머신러닝 ⊃ AI', '머신러닝 ⊃ AI ⊃ 딥러닝', '셋은 서로 무관'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: 'AI가 가장 큰 범주 · 그 안에 머신러닝 · 그 안에 딥러닝 · 생성형 AI는 딥러닝의 한 갈래',
        },
        {
          id: 'f2',
          question: '1970년대 첫 번째 AI 겨울의 원인으로 알맞은 것은?',
          options: ['XOR 문제 등 기술 한계와 연구비 삭감', '인터넷의 등장', '스마트폰 보급', 'ChatGPT 출시'],
          correctIndex: 0,
          timeLimitSec: 15,
          explanation: '기대가 성과를 앞지름 → 실망 · 연구비 삭감 · XOR 문제는 1980년대 다층 신경망(MLP)으로 해결',
        },
        {
          id: 'f3',
          question: '"창밖에서 레시피 불러주는 사람"이 챗봇이라면, "주방에 들어와 요리하는 사람"은?',
          options: ['검색엔진', '에이전트', '계산기', '키보드'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '에이전트 = 직접 만들고 · 고치고 · 실행하고 · 스스로 재시도하는 AI',
        },
        {
          id: 'f4',
          question: 'AI 시대 항공 정비에서 가장 대체하기 어려운 병목이자 자산은?',
          options: ['코드 문법 암기', '현장 지식과 판단', '빠른 타자 속도', '단순 기록 작업'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '병목은 기술이 아니라 현장 지식 · 정비 양식 · 규정 · 요령은 어떤 AI 서비스 메뉴판에도 없음',
        },
        {
          id: 'f5',
          question: 'AI가 알려준 정비 수치를 쓰기 전에 할 일은?',
          options: ['바로 작업', '친구에게 물어보기', '승인된 정비 매뉴얼로 확인', 'AI에게 한 번 더 묻기만'],
          correctIndex: 2,
          timeLimitSec: 15,
          explanation: '환각 = 그럴듯한 거짓 수치 가능 · 근거는 승인된 정비 매뉴얼',
        },
        {
          id: 'f6',
          question: '참여도 기반 추천 AI가 최대화하는 것은?',
          options: ['사용자의 행복', '클릭 · 시청 시간', '수면 시간', '학업 성적'],
          correctIndex: 1,
          timeLimitSec: 15,
          explanation: '지표 = 클릭 · 체류 시간 · AI는 주어진 지표만 최적화',
        },
        {
          id: 'f7',
          question: 'AI가 작성한 정비 점검표에 내가 서명했다. 결과에 대한 책임은?',
          options: ['AI', 'AI를 만든 회사', '확인하고 서명한 사람', '아무에게도 없음'],
          correctIndex: 2,
          timeLimitSec: 15,
          explanation: 'AI는 부조종사 · 기장은 나 · 판단과 서명의 책임 = 사람',
        },
      ],
    },

    // ── 마무리 ──
    'poll-feedback': {
      type: 'poll',
      id: 'poll-feedback',
      title: '소감 한마디',
      prompt: '오늘 특강을 한 단어로 남긴다면?',
      mode: 'wordcloud',
      anonymous: true,
    },
  },
  slides: buildSlides(),
};

function buildSlides(): Slide[] {
  const P0 = '입장 · 워밍업';
  const P1 = '1교시 · AI의 이해와 바이브코딩';
  const P2 = '2교시 · AI 윤리';
  const P3 = '3교시 · AI 시대 항공 진로';
  const P4 = '마무리';
  const S = (s: Slide) => s;
  const img = (id: string, part: number, partTitle: string, file: string, title: string, notes: string) =>
    S({ id, part, partTitle, layout: 'image', imageUrl: `/api/uploads/${file}`, title, notes });
  return [
    // ── 파트 0 · 입장·워밍업 (0:00–0:08) ──
    S({ id: 'g0-1', part: 0, partTitle: P0, layout: 'title',
      title: '경남항공고 AI 특강',
      subtitle: 'AI의 이해 · AI 윤리 · 항공 AI 진로 · 바이브코딩 | 50분 × 3교시',
      blocks: [
        { kind: 'p', text: '대상 : 경남항공고등학교 학생' },
        { kind: 'p', text: '강사 조성호 · 부산대학교 AI융합교육원 강사 / KODE KOREA(코드코리아) 대표' },
      ],
      notes: '입장 시간. 화면 QR·방 코드 안내 반복. 300명 입장 확인 후 시작. 와이파이 불안정 시 LTE 사용 안내. 닉네임은 실명 대신 별명 권장(개인정보 수칙 예고).' }),
    S({ id: 'g0-2', part: 0, partTitle: P0, layout: 'content',
      title: 'Contents',
      blocks: [
        { kind: 'bullet', text: '00 · 0:00–0:08 · 입장 · 워밍업 — 워드클라우드 · OX 퀴즈' },
        { kind: 'bullet', text: '01 · 0:08–0:50 · AI의 이해와 바이브코딩 — AI 개념 · 역사 · 현장 지식 · 첫 앱 제작' },
        { kind: 'note', text: '휴식 10분' },
        { kind: 'bullet', text: '02 · 1:00–1:50 · AI 윤리 — AI 위협 · 환경 비용 · 추천 알고리즘 · 공학윤리 · 주체성 · 앱 검증' },
        { kind: 'note', text: '휴식 10분' },
        { kind: 'bullet', text: '03 · 2:00–2:50 · AI 시대 항공 진로 — 일의 두 층 · 진로 로드맵 · 포트폴리오 완성' },
      ],
      notes: '30초. 흐름만. 바이브코딩 앱 하나를 3교시 내내 키운다는 점 강조.' }),
    S({ id: 'g0-3', part: 0, partTitle: P0, layout: 'big',
      title: '들어가기 전에…',
      subtitle: '코딩을 배운 적 없는 사람도 오늘 앱을 만들 수 있을까? · AI가 끝까지 대신할 수 없는 사람의 일은?',
      notes: '답 받지 않고 던지기만. 첫 질문은 1교시 끝 각자 폰의 앱으로, 둘째 질문은 3교시 "일의 두 층"에서 회수.' }),
    S({ id: 'g0-4', part: 0, partTitle: P0, layout: 'content',
      title: '학습 목표',
      blocks: [
        { kind: 'h', text: '목표 1 · 이해' },
        { kind: 'bullet', text: 'AI의 개념 · 역사 · 생성형 AI의 원리와 한계(환각) 이해' },
        { kind: 'bullet', text: 'AI 위협 · 환경 비용 · 추천 알고리즘 · 공학윤리 · 주체성 쟁점 판단' },
        { kind: 'h', text: '목표 2 · 제작' },
        { kind: 'bullet', text: '바이브코딩으로 항공 앱 제작 → 검증 → 개선' },
        { kind: 'bullet', text: '판단 · 책임 중심의 항공 진로 로드맵 작성' },
        { kind: 'callout', text: '최종 결과물 : 스마트폰에서 열리는 나의 진로 포트폴리오 앱' },
      ],
      notes: '1분. 목표 2의 결과물이 3교시 끝의 포트폴리오라는 점만 짚기.' }),
    S({ id: 'g0-5', part: 0, partTitle: P0, layout: 'big',
      title: 'AI 하면 떠오르는 단어는?',
      subtitle: '스마트폰으로 한 단어 입력',
      activityId: 'poll-warmup',
      notes: '2분. 익명 워드클라우드. 큰 단어 2~3개 읽어 주며 반응 유도. "챗GPT"가 크면 다음 퀴즈로 연결.' }),
    S({ id: 'g0-6', part: 0, partTitle: P0, layout: 'big',
      title: '몸풀기 OX 퀴즈',
      subtitle: '3문항 · 빠를수록 고득점 · 점수는 3교시 끝까지 누적',
      activityId: 'quiz-warmup',
      notes: '3분. 점수·리더보드 작동 확인용. 문항별 해설은 한 줄로만. 3번 문항 정답 공개 후 "1교시에 직접 확인" 예고.' }),

    // ── 파트 1 · 1교시 (0:08–0:50) ──
    S({ id: 'g1-1', part: 1, partTitle: P1, layout: 'section',
      title: '01 · 1교시',
      subtitle: '0:08 – 0:50 · AI의 이해 · 현장 지식 · 바이브코딩' }),
    img('g1-2', 1, P1, 'gnaero-aio-02.jpg', '당신이 생각하는 인공지능?',
      '1분. 질문만 던지기 — "우리가 알고 있는 인공지능은 어떻게 작동하는 것일까?" 워드클라우드 결과(챗GPT 등)와 연결. 답은 이어지는 정의·범주 슬라이드에서.'),
    S({ id: 'g1-3', part: 1, partTitle: P1, layout: 'content',
      title: 'AI = 인간의 지적 능력을 기계로 구현',
      blocks: [
        { kind: 'p', text: '1-1 · AI란?' },
        { kind: 'bullet', text: '정의 : 인간의 지적 능력의 일부 또는 전체를 기계로 구현' },
        { kind: 'bullet', text: '지능 : 본능 대신 생각하고 이해하여 행동하는 능력' },
        { kind: 'bullet', text: '인공 : 사람이 만든 것' },
        { kind: 'bullet', text: '질문 : 기계도 지능을 가질 수 있을까? · "지능을 가졌다"의 기준은?' },
        { kind: 'callout', text: '핵심 : 지능의 기준에 따라 AI의 범위도 달라짐' },
      ],
      notes: '2분. 질문 두 개는 손들기로만 반응 확인. 정답 없는 질문 — 튜링 테스트(역사 슬라이드)에서 "측정 가능한 기준"으로 다시 연결.' }),
    S({ id: 'g1-4', part: 1, partTitle: P1, layout: 'twocol',
      title: '약인공지능 · 강인공지능',
      blocks: [
        { kind: 'h', text: '약인공지능(Weak AI)' },
        { kind: 'bullet', text: '지능을 가진 도구' },
        { kind: 'bullet', text: '규칙 · 알고리즘 · 데이터 기반 학습 · 특정 분야 전용' },
        { kind: 'bullet', text: '예 : 알파고 · 번역기 · 자율주행 보조' },
        { kind: 'h', text: '강인공지능(Strong AI)' },
        { kind: 'bullet', text: '인간처럼 사고하고 행동하는 시스템' },
        { kind: 'bullet', text: '정해진 규칙을 벗어나 능동적으로 학습 · 다양한 분야에 범용 활용' },
        { kind: 'bullet', text: '현재 미실현 · 연구 목표(AGI)' },
      ],
      notes: '2분. 알파고 = 바둑만 잘하는 약인공지능의 대표 사례. ChatGPT도 범용처럼 보이지만 학계 다수 견해는 아직 강인공지능(AGI) 아님 — 단정 대신 "논쟁 중"으로. AGI는 2교시 구글 DeepMind의 AGI 위험 분류에서 다시 등장.' }),
    img('g1-5', 1, P1, 'gnaero-aio-07.jpg', 'AI의 범주 — AI ⊃ 머신러닝 ⊃ 인공신경망 ⊃ 딥러닝',
      '1분. 가장 큰 원 = AI, 그 안에 머신러닝(ML), 인공신경망(ANN), 딥러닝(DL). 다음 슬라이드에서 한 줄 정의 + 생성형 AI의 위치 추가.'),
    S({ id: 'g1-6', part: 1, partTitle: P1, layout: 'content',
      title: 'AI ⊃ 머신러닝 ⊃ 딥러닝 ⊃ 생성형 AI',
      blocks: [
        { kind: 'bullet', text: 'AI : 지적 능력을 기계로 구현하는 모든 기술' },
        { kind: 'bullet', text: '머신러닝(ML) : 데이터에서 규칙을 스스로 학습 → 예측' },
        { kind: 'bullet', text: '인공신경망(ANN) : 뇌의 뉴런 연결을 흉내 낸 계산 구조' },
        { kind: 'bullet', text: '딥러닝(DL) : 층을 깊게 쌓은 인공신경망' },
        { kind: 'bullet', text: '생성형 AI : 딥러닝으로 글 · 그림 · 코드를 새로 만드는 갈래' },
        { kind: 'callout', text: '예 : 알파고 · ChatGPT = 딥러닝 기반 약인공지능' },
      ],
      notes: '1분. 빅데이터 = 대량 데이터 자체, 머신러닝 = 그 데이터에서 규칙을 학습하는 방법 — 질문 나오면 구분.' }),
    S({ id: 'g1-7', part: 1, partTitle: P1, layout: 'content',
      title: 'AI 역사 = 기대와 겨울의 반복',
      blocks: [
        { kind: 'bullet', text: '1950 튜링 테스트 · 1956 다트머스 회의("AI" 용어 탄생)' },
        { kind: 'bullet', text: '1956~1974 첫 번째 황금기 : "20년 안에 기계가 사람의 모든 일 수행" 낙관' },
        { kind: 'bullet', text: '1974~1980 첫 번째 겨울 : XOR 문제 · 연산량 한계 → 연구비 삭감' },
        { kind: 'bullet', text: '1980년대 두 번째 황금기 : 다층 신경망(MLP)으로 XOR 해결 · 전문가 시스템' },
        { kind: 'bullet', text: '1987~1993 두 번째 겨울 : 신경망 학습 한계 · AI 하드웨어 시장 붕괴' },
        { kind: 'bullet', text: '2012~ 딥러닝 부활 → 2016 알파고 → 2022 ChatGPT' },
        { kind: 'callout', text: '핵심 : 기대 → 실망 → 겨울 → 돌파의 반복 · 현재 = 세 번째 붐' },
      ],
      notes: '2분. 이어지는 사진 4장(튜링·다트머스·XOR·힌턴)을 30초씩 넘기며 한 줄씩 설명. 교훈: 과대 기대는 늘 실망을 불렀음 → 지금 AI도 할 수 있는 것과 없는 것 구분 필요.' }),
    img('g1-8', 1, P1, 'gnaero-aio-14.jpg', '튜링 테스트 (1950)',
      '30초. 앨런 튜링 — 측정할 수 있는 실험으로 지능의 정의를 내림. 대화 상대가 사람인지 기계인지 구별 못 하면 지능이 있다고 봄. 1-1의 "지능의 기준" 질문과 연결.'),
    img('g1-9', 1, P1, 'gnaero-aio-16.jpg', '다트머스 회의 (1956)',
      '30초. 존 매카시 등이 다트머스 회의에서 "인공지능(AI)" 용어 제안 → 학문 분야 탄생. 이후 첫 번째 황금기의 낙관.'),
    img('g1-10', 1, P1, 'gnaero-aio-18.jpg', '첫 번째 겨울 — XOR 문제 (1974~1980)',
      '30초. 단층 퍼셉트론은 XOR(둘 중 하나만 참)을 직선 하나로 나눌 수 없음 + 당시 컴퓨터로 감당 못 할 연산량 → 기대가 무너지며 연구비 삭감.'),
    img('g1-11', 1, P1, 'gnaero-aio-20.jpg', '두 번째 황금기 — 제프리 힌턴과 다층 신경망',
      '30초. 층을 여러 개 쌓은 다층 신경망(MLP)과 역전파 학습으로 XOR 문제 해결. 이 계보가 2012년 이후 딥러닝, 지금의 생성형 AI로 이어짐.'),
    S({ id: 'g1-12', part: 1, partTitle: P1, layout: 'content',
      title: '생성형 AI = 다음에 올 말을 예측하는 모델',
      blocks: [
        { kind: 'p', text: '1-2 · 생성형 AI' },
        { kind: 'bullet', text: '방대한 글 · 이미지 · 코드 학습 → 가장 그럴듯한 다음 조각을 하나씩 생성' },
        { kind: 'bullet', text: '"오늘 날씨가 ___" → "맑다" · "좋다" 확률 예측의 반복' },
        { kind: 'bullet', text: '생성 대상 : 글 · 이미지 · 음성 · 영상 · 코드' },
        { kind: 'callout', text: '핵심 : 검색이 아닌 생성 → 그럴듯함과 정확함은 별개' },
      ],
      notes: '2분. 워밍업 1번 문항과 연결. "정확함은 별개"는 2교시 환각 복선.' }),
    S({ id: 'g1-13', part: 1, partTitle: P1, layout: 'twocol',
      title: '잘하는 것 · 못하는 것',
      blocks: [
        { kind: 'h', text: '잘하는 것' },
        { kind: 'bullet', text: '초안 · 아이디어 빠른 생성' },
        { kind: 'bullet', text: '요약 · 번역 · 코드 작성' },
        { kind: 'bullet', text: '지치지 않는 반복 수정' },
        { kind: 'h', text: '못하는 것' },
        { kind: 'bullet', text: '최신 · 정확한 사실 보장' },
        { kind: 'bullet', text: '결과에 대한 책임' },
        { kind: 'bullet', text: '환각 — 그럴듯한 거짓 답' },
      ],
      notes: '1분. 오른쪽 열은 2교시에서 다시 다룬다고만 언급.' }),
    img('g1-14', 1, P1, 'gnaero-aio-28.jpg', 'AI 활용 사례 — 자동화 · 오토파일럿',
      '1분. 자율주행 자동차·무인기 = 약인공지능 활용 사례. 항공기 자동조종(오토파일럿)은 수십 년 된 규칙 기반 자동화로 AI와는 구분 — 자동화가 발전해도 비행 판단과 책임은 조종사. 2교시 "마젠타 라인의 아이들" 복선.'),
    img('g1-15', 1, P1, 'gnaero-kepco-01.jpg', '챗봇 = 창밖에서 레시피 불러주는 사람 · 에이전트 = 주방에 들어와 요리하는 사람',
      '1분. 챗봇 = 창밖에서 레시피를 불러주는 사람 · 에이전트 = 주방에 직접 들어와 요리하는 사람. 에이전트는 직접 만들고, 고치고, 실행하고, 스스로 재시도. 오늘 바이브코딩 = 주방에 들어온 요리사에게 일을 맡기는 방식.'),
    img('g1-16', 1, P1, 'gnaero-kepco-03.jpg', 'SaaS = 메뉴판에 있는 것만 · 에이전트 = 우리 주방에서 필요한 것을 만듦',
      '1분. SaaS = 남이 지은 식당, 메뉴판에 있는 것만 주문 가능. 에이전트 = 우리 주방에 온 요리사, 없으면 만들어 씀. 메뉴판에 있으면 식당이 더 싸고 빠름 — 문제는 메뉴판에 없는 우리 일. 항공 정비의 양식·규정·현장 요령은 어떤 AI 서비스 메뉴판에도 없음.'),
    S({ id: 'g1-17', part: 1, partTitle: P1, layout: 'big',
      title: '병목은 기술이 아니라 현장 지식',
      subtitle: 'AI에게 일터를 내주는 시대 · 항공 정비 현장 지식 = 가장 큰 자산',
      blocks: [
        { kind: 'bullet', text: '정비 양식 · 규정 · 현장 요령 = AI 서비스가 갖고 있지 않은 지식' },
        { kind: 'bullet', text: '에이전트 시대에 대체 불가능한 것 = 코딩이 아니라 현장 지식' },
        { kind: 'bullet', text: 'AI가 만들고 → 현장 전문가가 판단하고 검수' },
      ],
      notes: '2분. KEPCO 특강 핵심 문장을 항공 정비로 옮긴 것. 전공 실습·매뉴얼 공부 = AI 시대의 경쟁력. 개발자가 될 필요는 없음 — 3교시 "일의 두 층"의 복선.' }),
    S({ id: 'g1-18', part: 1, partTitle: P1, layout: 'content',
      title: 'AI 그림 코딩 = 모양 + 색 + 글자',
      blocks: [
        { kind: 'p', text: '1-3 · 그림도 코드' },
        { kind: 'bullet', text: 'SVG : 원 · 선 · 다각형을 좌표로 적은 그림 코드 → 확대해도 깨지지 않음' },
        { kind: 'bullet', text: '모양 : 무엇을 어떤 틀 안에 (예: 남색 원 안에 은색 날개)' },
        { kind: 'bullet', text: '색 · 글자 : 주요 색 2~3개 · 넣을 문구 (예: "2040 UAM")' },
        { kind: 'callout', text: '원칙 : 구체적 설명 → 원하는 그림에 근접 · 이 원리가 곧 바이브코딩' },
      ],
      notes: '30초. 사진이 아니라 코드로 그린 그림 → 엠블럼·배지·아이콘에 강함. 예시 칩 그대로 눌러도 된다고 안내 후 바로 실습.' }),
    S({ id: 'g1-19', part: 1, partTitle: P1, layout: 'big',
      title: 'AI 그림 코딩 — 2040년 미래 항공기 엠블럼',
      subtitle: '모양 · 색 · 글자를 넣어 설명 · 1인 3장',
      activityId: 'image-future-aircraft',
      notes: '4분. 1인 3장. 생성 5~10초. 잘 나온 작품 2개를 구두 소개하며 "이 그림은 사실 수백 줄의 코드" 강조 → 바이브코딩으로 연결.' }),
    S({ id: 'g1-20', part: 1, partTitle: P1, layout: 'content',
      title: '바이브코딩(Vibe Coding)',
      blocks: [
        { kind: 'p', text: '1-4 · 바이브코딩' },
        { kind: 'bullet', text: '원하는 기능을 말로 설명 → AI가 코드 작성 → 실행 결과 확인 → 말로 수정' },
        { kind: 'bullet', text: '2025년 AI 연구자 안드레이 카파시(Andrej Karpathy)가 처음 쓴 표현' },
        { kind: 'bullet', text: '코드 문법 암기보다 원하는 결과를 정확히 설명하는 능력이 중요' },
        { kind: 'callout', text: '비유 : 챗봇 = 창밖에서 레시피 불러주는 사람 · 에이전트 = 주방에 들어와 요리하는 사람' },
      ],
      notes: '1분. 들어가기 전 첫 질문 다시 꺼내기. 오늘 만든 앱은 폰 브라우저에서 바로 실행.' }),
    S({ id: 'g1-21', part: 1, partTitle: P1, layout: 'content',
      title: '좋은 요청 공식 = 누가 + 무엇을 + 어떻게 보이게',
      blocks: [
        { kind: 'p', text: '1-5 · 요청 공식' },
        { kind: 'bullet', text: '누가 · 무엇을 · 어떻게 보이게 : 항공정비과 학생 · 외부 점검 10개 체크 · 큰 버튼과 진행률' },
        { kind: 'quote', text: '항공정비과 학생이 실습 중에 쓸 외부 점검 체크리스트 앱 만들어줘. 항목 10개를 체크하면 진행률이 보이고, 버튼은 크게, 하늘색 배경으로.' },
        { kind: 'bullet', text: '후배에게 일 시키듯 : 완성 사진 먼저 · 합격 조건 3줄 · 샘플 검수' },
        { kind: 'bullet', text: '진행 : 아이디어 칩 선택 → 생성(6~8초) → 직접 실행 → 마음에 안 드는 점 하나 수정' },
        { kind: 'callout', text: '수정 원칙 : 한 번에 하나씩 · 구체적으로 · 1인 6회' },
      ],
      notes: '2분. 나쁜 예 "앱 만들어줘"와 비교해서 말로만 설명. 강사 폰 미러링으로 체크리스트 앱 짧게 실시연(생성 6~8초, 코드가 써지는 화면 표시).' }),
    img('g1-22', 1, P1, 'gnaero-kepco-06.jpg', '완성 사진 · 합격 조건 3줄 · 샘플 검수',
      '1분. AI에게 일 시키기 = 후배에게 일 시키기와 같은 방식. 완성 사진(원하는 결과 예시) 먼저 · 합격 조건 3줄(간 보는 사람 = 검증기) · 100개 만들면 무작위 3개는 사람이 직접 검수. 개발자가 될 필요 없음 — 이미 선배가 후배에게 하던 일.'),
    S({ id: 'g1-23', part: 1, partTitle: P1, layout: 'content',
      title: '바이브코딩 안전 수칙',
      blocks: [
        { kind: 'bullet', text: '실명 · 전화번호 · 주소 · 사진 등 개인정보 입력 금지' },
        { kind: 'bullet', text: '앱 속 수치 · 정보 = AI 생성물 → 그대로 믿기 금지' },
        { kind: 'bullet', text: '실제 정비 작업에 사용 금지 · 학습용' },
        { kind: 'bullet', text: '다른 사람을 비방 · 조롱하는 앱 금지' },
        { kind: 'callout', text: '원칙 : 만든 사람 = 확인할 책임이 있는 사람' },
      ],
      notes: '30초. 2교시 윤리 파트 예고. 부적절 요청은 자동 차단된다는 점도 안내.' }),
    S({ id: 'g1-24', part: 1, partTitle: P1, layout: 'big',
      title: '연습 단계 1 · 13분 — 나의 첫 항공 앱',
      subtitle: '바이브코딩 Lv.1',
      activityId: 'vibe-lv1',
      blocks: [
        { kind: 'bullet', text: '1. 아이디어 선택 또는 직접 구상 (누가 · 무엇을 · 어떻게 보이게)' },
        { kind: 'bullet', text: '2. 요청 입력 → 앱 생성 → 직접 실행' },
        { kind: 'bullet', text: '3. 수정 요청 2회 이상 (한 번에 하나씩)' },
        { kind: 'callout', text: '합격 조건 : 폰에서 동작하는 앱 1개 + 수정 2회' },
        { kind: 'note', text: '확인 포인트 : 버튼 · 입력이 실제로 동작하는지 · 진행 : 10분 경과 시 마무리 안내' },
      ],
      notes: '13분. 300명 동시 생성 → 대기 시간 길어질 수 있음, 연타 금지 안내. 강당 와이파이가 혼잡하면 LTE 사용 또는 2인 1조(폰 1대)로 전환. 막힌 학생은 아이디어 칩 사용. 앱은 자동 저장, 2교시에 이어서 사용. 7분 지점에 앱 갤러리로 잘 만든 앱 2개 소개.' }),
    S({ id: 'g1-25', part: 1, partTitle: P1, layout: 'content',
      title: '01 정리',
      blocks: [
        { kind: 'bullet', text: 'AI = 지적 능력의 기계 구현 · AI ⊃ ML ⊃ DL ⊃ 생성형 AI · 역사 = 기대와 겨울의 반복' },
        { kind: 'bullet', text: '생성형 AI = 다음 조각 예측 · 그럴듯함 ≠ 정확함' },
        { kind: 'bullet', text: '병목은 기술이 아니라 현장 지식 · 바이브코딩 = 말로 설명 → 생성 → 확인 → 하나씩 수정' },
        { kind: 'note', text: '휴식 10분 · 1:00 시작 · 다음 02 · AI 윤리' },
      ],
      notes: '1분. 앱 저장됨 안내. 쉬는 시간에도 입장 상태 유지(페이지 닫아도 재입장 가능).' }),
    S({ id: 'g1-26', part: 1, partTitle: P1, layout: 'big',
      title: '쉬는 시간 10분',
      subtitle: '1:00 시작 · 다음 02 · AI 윤리 — 내 앱, 믿어도 될까?',
      notes: '타이머 표시. 폰 배터리 확인 안내.' }),

    // ── 파트 2 · 2교시 (1:00–1:50) ──
    S({ id: 'g2-1', part: 2, partTitle: P2, layout: 'section',
      title: '02 · 2교시',
      subtitle: '1:00 – 1:50 · AI 윤리' }),
    S({ id: 'g2-2', part: 2, partTitle: P2, layout: 'big',
      title: '1교시에 만든 앱에서 틀린 정보가 나온다면, 책임은 누구에게?',
      subtitle: 'AI · 앱을 만든 나 · 앱을 쓴 사람',
      notes: '1분. 손들기로 반응만. 정답 공개 없이 공학윤리(에어캐나다 판결)와 2교시 끝 퀴즈에서 회수.' }),
    S({ id: 'g2-3', part: 2, partTitle: P2, layout: 'content',
      title: '환각(Hallucination)',
      blocks: [
        { kind: 'p', text: '2-1 · 환각' },
        { kind: 'bullet', text: '정의 : 사실이 아닌 내용을 사실처럼 생성하는 현상' },
        { kind: 'bullet', text: '원인 : 정답 검색이 아닌 그럴듯한 다음 말 예측' },
        { kind: 'bullet', text: '특징 : 틀린 답도 자신 있는 말투 → 겉보기로 구분 불가' },
        { kind: 'bullet', text: '항공 현장 위험 : 존재하지 않는 부품 번호 · 토크 값 · 절차 생성 가능' },
        { kind: 'callout', text: '기준 : 정비 수치 · 절차의 근거 = 승인된 정비 매뉴얼' },
      ],
      notes: '2분. 실제 매뉴얼 수치 예시는 들지 말 것(가상 수치도 오해 소지). 실제 판례 사례는 공학윤리 슬라이드에서.' }),
    S({ id: 'g2-4', part: 2, partTitle: P2, layout: 'big',
      title: '환각 OX — 정비 매뉴얼 수치',
      subtitle: '그럴듯한 AI 답, 바로 써도 될까?',
      activityId: 'ox-hallucination',
      notes: '2분. 정답 X. 해설 후 "그럴듯함 ≠ 정확함" 한 번 더.' }),
    S({ id: 'g2-5', part: 2, partTitle: P2, layout: 'content',
      title: 'AI 시대의 핵심 역량 = 비판적 사고',
      subtitle: 'IBM Technology · Jeff Crume, 「AI & Education」 (2026) · 4:54–6:40',
      youtubeUrl: `${IBM_VIDEO}&start=294&end=400`,
      blocks: [
        { kind: 'quote', text: '"We\'re going to have to be the judge." → 판단은 결국 사람의 몫' },
        { kind: 'quote', text: '"The critical skill is critical thinking." → 가장 중요한 역량 = 비판적 사고' },
        { kind: 'note', text: '영어 영상 · 한국어 자동 자막' },
      ],
      notes: '3분. 영상 약 1분 45초. 자막 설정 → 자동 번역 → 한국어. 요지: 유연성·창의성도 필요하지만 AI는 틀린 말·쓸모없는 말도 할 수 있어 결국 사람이 판단자 · 의도치 않은 결과까지 생각. 재생 불가 시 인용 2줄만 읽고 넘어가기.' }),
    S({ id: 'g2-6', part: 2, partTitle: P2, layout: 'content',
      title: '구글이 직접 밝힌 AI 위협',
      blocks: [
        { kind: 'p', text: '2-2 · AI 위협 · 딥페이크' },
        { kind: 'bullet', text: '실제 악용 약 200건 분석 : 1위 수법 = 사람 사칭(20% 이상)' },
        { kind: 'bullet', text: '해킹보다 누구나 쓰는 생성 기능(가짜 얼굴 · 목소리 · 계정)의 악용이 대부분' },
        { kind: 'bullet', text: '딥페이크 화상회의 속 가짜 임원 → 약 2,600만 달러 송금 피해 (2024 · 홍콩)' },
        { kind: 'bullet', text: 'AGI 4대 위험 : 오용 · 목표 불일치 · 사고 · 구조적 위험' },
        { kind: 'callout', text: '대처 : 출처 확인 · 끊고 다시 걸기 · 가족 암호 · 실존 인물 합성 금지 · 피해 시 증거 보존 후 신고' },
        { kind: 'note', text: '출처 : Google DeepMind 외 「Generative AI Misuse」(2024) · 「Taking a responsible path to AGI」(2025)' },
      ],
      notes: '3분. 질문: 엄마 목소리로 "급하니까 돈 보내줘" 전화가 오면? → 끊고 다시 걸기·가족 암호. 목표 불일치 예: 영화표 예매를 맡겼더니 매진 좌석을 얻으려 예매 시스템을 해킹(DeepMind 예시). 타인 얼굴·목소리 무단 합성 = 인격권 침해·처벌 대상 가능.' }),
    S({ id: 'g2-7', part: 2, partTitle: P2, layout: 'content',
      title: '미국 대학생이 느끼는 AI 위협',
      blocks: [
        { kind: 'p', text: '2-3 · 또래의 불안' },
        { kind: 'bullet', text: '미국 대학생 85% 과제에 AI 사용 · 55% 진로 악영향 예상 (Inside Higher Ed, 2025)' },
        { kind: 'bullet', text: '약 40% AI 의존 걱정 · 예술 · 미디어 전공 진로 불안 75% (Inside Higher Ed, 2026)' },
        { kind: 'bullet', text: '미국 Z세대(14~29세) 42% "비판적 사고력 저하" 우려 (Gallup, 2026)' },
        { kind: 'bullet', text: '"위험이 이익보다 큼" 37% → 48% 증가 (Gallup, 2026)' },
        { kind: 'callout', text: '핵심 : 가장 많이 쓰는 세대가 가장 크게 걱정' },
      ],
      notes: '2분. [시간 부족 시 생략 가능] Gallup 수치는 대학생만이 아닌 14~29세 Z세대 전체 기준. 질문: 항공 정비·운항 분야는 어떨까? → 3교시 "일의 두 층"에서 회수.' }),
    S({ id: 'g2-8', part: 2, partTitle: P2, layout: 'content',
      title: 'AI의 보이지 않는 환경 비용',
      blocks: [
        { kind: 'p', text: '2-4 · 환경' },
        { kind: 'bullet', text: '데이터센터 전력 약 415TWh(2024) → 약 945TWh(2030 전망) ≈ 일본 한 나라 소비량 (IEA, 2025)' },
        { kind: 'bullet', text: 'Gemini 질문 1회 : 전력 0.24Wh · 물 0.26mL (구글 자체 측정, 2025)' },
        { kind: 'bullet', text: '1회당 효율 개선에도 구글 탄소 배출 2019년 대비 약 51% 증가 (구글 환경보고서, 2025)' },
        { kind: 'bullet', text: 'GPT-3 학습 과정에서 물 약 70만 L 증발 추정 (UC Riverside, 2023)' },
        { kind: 'callout', text: '핵심 : 1회 비용은 작아도 하루 수십억 번 → 전체 사용량 급증' },
      ],
      notes: '3분. 두 물 수치는 측정 범위가 달라 직접 비교 금지(구글 = 데이터센터 사용분 중심 자체 측정, UCR = 발전소 냉각수 포함 추정). 질문: 전교생이 하루 10번씩 1년 묻는다면? 효율이 좋아질수록 더 많이 쓰게 되는 현상(제번스 역설) 언급 가능.' }),
    S({ id: 'g2-9', part: 2, partTitle: P2, layout: 'content',
      title: '클릭을 최적화하는 AI · 행복은 목표에 없는 AI',
      blocks: [
        { kind: 'p', text: '2-5 · 돈과 클릭을 좇는 추천 알고리즘' },
        { kind: 'bullet', text: '미국 10대 최대 95% SNS 사용 · 하루 3시간 초과 시 우울 · 불안 위험 2배 (미 공중보건위생국장 권고, 2023)' },
        { kind: 'bullet', text: '메타 내부 연구 : 10대 소녀 3명 중 1명 신체 이미지 고민 악화 (2019 내부 자료 · 2021 공개)' },
        { kind: 'bullet', text: '참여도 기반 추천 → 분노 · 적대 콘텐츠 증폭 · 사용자 만족과 불일치 (PNAS Nexus, 2025)' },
        { kind: 'bullet', text: '관계 비용 : 가족 · 친구와의 시간과 대화가 화면 체류 시간과 경쟁' },
        { kind: 'callout', text: '핵심 : 추천 AI의 지표 = 클릭 · 체류 시간 = 광고 수익 · 사용자의 행복은 목표에 없음' },
      ],
      notes: '3분. 질문: 쇼츠 "딱 하나만" 보다가 1시간 지난 경험? 그 추천 AI의 목표는 성적일까, 시청 시간일까. 메타는 "맥락 무시한 해석"이라 반박 — 내부 설문이지 인과 증명 아님. 구글 DeepMind의 "목표 불일치"와 같은 구조.' }),
    S({ id: 'g2-10', part: 2, partTitle: P2, layout: 'content',
      title: 'AI가 틀려도 책임은 사람에게 ① 코드와 판례',
      blocks: [
        { kind: 'p', text: '2-6 · 공학윤리' },
        { kind: 'bullet', text: 'AI 코딩 도우미 사용 → 보안 취약 코드 증가 + "안전하다"는 근거 없는 자신감 (Stanford, 2023)' },
        { kind: 'bullet', text: 'AI 생성 코드 19.7%에 존재하지 않는 패키지 이름 → 해커가 먼저 등록하는 "슬롭스쿼팅" (USENIX Security, 2025)' },
        { kind: 'bullet', text: 'Mata v. Avianca(2023) : ChatGPT가 지어낸 가짜 판례 6건 제출 → 변호사 5,000달러 제재 · 항공사 상대 소송' },
        { kind: 'callout', text: '원칙 : 공학 윤리강령 제1원칙 = 공공의 안전 · 건강 · 복지 최우선 (NSPE · IEEE)' },
      ],
      notes: '2분. 바이브코딩 앱도 같은 문제 → Lv.2 검증 실습 예고. 아비앙카 = 항공사, 기내 서빙 카트에 무릎을 다친 승객의 소송. ChatGPT에 "진짜 판례냐" 묻자 "그렇다"고 답했으나 거짓.' }),
    S({ id: 'g2-11', part: 2, partTitle: P2, layout: 'content',
      title: 'AI가 틀려도 책임은 사람에게 ② 항공 사례',
      blocks: [
        { kind: 'bullet', text: 'Moffatt v. Air Canada(2024) : 챗봇의 유족 할인 운임 오안내 → 항공사 배상 판결' },
        { kind: 'bullet', text: '"챗봇은 별개의 법적 주체" 주장 기각 → 챗봇 안내도 회사 책임' },
        { kind: 'bullet', text: '보잉 737 MAX : 받음각 센서 1개에 의존한 자동 기수 하강 시스템(MCAS) · 초기 조종사 매뉴얼에 설명 누락' },
        { kind: 'bullet', text: '2018 · 2019 두 차례 추락 · 346명 사망 · 약 20개월 운항 금지' },
        { kind: 'callout', text: '교훈 : 사람이 이해하지 못하는 자동화 = 안전 위험 · MCAS = AI 아닌 규칙 기반 자동화' },
      ],
      notes: '3분. 질문: 정비사가 AI가 작성한 점검표에 서명 → 사고 시 책임은? 에어캐나다 배상액은 약 812캐나다달러 — 액수보다 "챗봇도 회사의 일부"라는 판단이 핵심. 737 MAX는 AI 사고가 아님을 분명히 — 자동화를 조종사가 충분히 알 수 없게 설계·교육한 공학윤리 문제.' }),
    S({ id: 'g2-12', part: 2, partTitle: P2, layout: 'content',
      title: '생각을 AI에게 맡기면 생기는 일',
      blocks: [
        { kind: 'p', text: '2-7 · 생각하는 힘과 주체성' },
        { kind: 'bullet', text: 'ChatGPT로 쓴 에세이 : 뇌 연결성 최저 · 다수가 자기 글 한 문장 인용 실패 (MIT 미디어랩, 2025 · 동료심사 전 소규모 연구)' },
        { kind: 'bullet', text: 'AI를 믿을수록 비판적 사고 감소 · 자기 능력을 믿을수록 증가 (Microsoft · CMU, CHI 2025)' },
        { kind: 'bullet', text: 'AI 사용 빈도 ↑ → 비판적 사고 점수 ↓ · 연결고리 = 인지적 떠넘기기 · 17~25세 의존도 최고 (Gerlich, 2025)' },
        { kind: 'callout', text: '핵심 : 생각하는 과정을 건너뛰면 기억 · 주인의식 약화 가능' },
      ],
      notes: '2분. 세 연구 모두 인과 증명이 아닌 경고 수준 — MIT는 참가자 54명 프리프린트, 나머지는 설문·상관 연구. "AI가 뇌를 망가뜨린다"는 과장 금지. MIT의 "83%" 수치는 요약 보도 기준이라 슬라이드에서는 "다수"로 표기.' }),
    S({ id: 'g2-13', part: 2, partTitle: P2, layout: 'content',
      title: 'AI는 부조종사 · 기장은 나',
      blocks: [
        { kind: 'bullet', text: '마젠타 라인의 아이들 : 자동조종 화면의 경로선만 따라가다 수동 비행 능력을 잃는 조종사' },
        { kind: 'bullet', text: 'FAA 보고서(2013) : 자동화 과의존 · 수동 조종 기술 저하 · 자기만족(complacency)을 주요 취약점으로 지적' },
        { kind: 'bullet', text: 'FAA 결론 : 비행경로 관리 책임 = 언제나 조종사' },
        { kind: 'bullet', text: '적용 : 과제 · 코드 · 정비 판단 = AI 초안 → 내가 이해 · 검증 · 결정' },
        { kind: 'callout', text: '원칙 : 도구는 맡겨도 판단과 책임은 맡기지 않음' },
      ],
      notes: '2분. 1997년 아메리칸항공 기장 Warren Vanderburgh의 교육 강연에서 유래한 표현. 질문: 자동조종이 꺼졌을 때 직접 몰 수 있는 조종사와 화면만 따라가는 조종사 중 누구 비행기를 탈까? 공부에서의 "자동조종"은 무엇일까?' }),
    S({ id: 'g2-14', part: 2, partTitle: P2, layout: 'content',
      title: '할 수 있다고 해서 해도 되는 것은 아님',
      subtitle: 'IBM Technology · Jeff Crume, 「AI & Education」 (2026) · 12:10–13:02',
      youtubeUrl: `${IBM_VIDEO}&start=730&end=782`,
      blocks: [
        { kind: 'quote', text: '"Just because you can do something doesn\'t mean you should do something." → 할 수 있다고 해서 해도 되는 것은 아님' },
        { kind: 'quote', text: '"Think about unintended consequences." → 의도하지 않은 결과까지 생각' },
        { kind: 'note', text: '필요 역량 = AI 리터러시(할 수 있는 것 · 없는 것) + 윤리' },
      ],
      notes: '2분. [시간 부족 시 생략 가능 — 결론 한 줄만 말로] 영상 약 50초 · 한국어 자동 자막. 앞의 환경·추천 알고리즘·공학윤리를 전부 "할 수 있다 ≠ 해도 된다"로 묶어 정리.' }),
    S({ id: 'g2-15', part: 2, partTitle: P2, layout: 'content',
      title: '항공 안전 문화 = Just Culture',
      blocks: [
        { kind: 'bullet', text: '정직한 실수 보고 → 처벌보다 원인 분석 · 절차 개선' },
        { kind: 'bullet', text: '고의 위반 · 중대한 부주의 → 책임 추궁' },
        { kind: 'callout', text: '적용 : AI 결과를 검증하지 않은 실수도 보고 · 공유 대상' },
      ],
      notes: '1분. 항공 분야가 보고 문화를 중시하는 이유 한 줄. 다음 역할극 도입.' }),
    S({ id: 'g2-16', part: 2, partTitle: P2, layout: 'big',
      title: '연습 단계 2 · 7분 — AI 사고 조사위원회',
      subtitle: '가상 사례 · 조사위원이 되어 근본 원인 찾기',
      activityId: 'roleplay-investigation',
      blocks: [
        { kind: 'bullet', text: '상황 : 정비사가 AI 챗봇이 알려준 토크 값으로 작업 → 다음 점검에서 조임 부족 발견' },
        { kind: 'bullet', text: '1. 무슨 일이 있었는지 질문' },
        { kind: 'bullet', text: '2. 작업 전 확인 절차 질문' },
        { kind: 'callout', text: '합격 조건 : 정비사가 근본 원인을 직접 인정 → 미션 클리어 보너스 500점' },
        { kind: 'note', text: '진행 : 4분 경과 시 힌트 — "매뉴얼로 확인했나요?"' },
      ],
      notes: '7분. 가상 사례임을 명확히. 미션 클리어 학생 수 확인, 클리어한 학생 질문 1개 구두 공유. 결론: 원인은 AI 오류가 아닌 검증 절차 누락.' }),
    S({ id: 'g2-17', part: 2, partTitle: P2, layout: 'big',
      title: '연습 단계 3 · 7분 — 내 앱 검증하기',
      subtitle: '바이브코딩 Lv.2 · 1교시 앱 불러오기',
      activityId: 'vibe-lv2',
      blocks: [
        { kind: 'bullet', text: '1. "틀린 정보나 버그 찾아줘" 요청' },
        { kind: 'bullet', text: '2. 찾은 문제 하나 수정' },
        { kind: 'bullet', text: '3. 검증 기능 추가 : 출처 표시 · 확인 체크 칸 · 입력값 경고' },
        { kind: 'callout', text: '합격 조건 : 수정 1회 이상 + 검증 기능 1개 추가' },
        { kind: 'note', text: '확인 포인트 : AI가 찾은 버그가 진짜 버그인지 직접 눌러 확인' },
      ],
      notes: '7분. 1교시 앱이 자동으로 불러와짐. 앱이 없는 학생은 새로 만들기. AI가 찾은 버그 목록도 틀릴 수 있음 = 검증의 검증.' }),
    S({ id: 'g2-18', part: 2, partTitle: P2, layout: 'big',
      title: 'AI 윤리 퀴즈',
      subtitle: '5문항 · 오늘 본 연구 · 판례 · 통계',
      activityId: 'quiz-ethics2',
      notes: '4분. 문항당 20초 + 해설 한 줄. 5번(에어캐나다)에서 2교시 첫 질문 "책임은 누구에게?" 회수.' }),
    S({ id: 'g2-19', part: 2, partTitle: P2, layout: 'content',
      title: '02 정리',
      blocks: [
        { kind: 'bullet', text: '위협 = 환각 · 사칭 · 딥페이크 · 환경 비용 · 클릭만 좇는 추천 알고리즘' },
        { kind: 'bullet', text: '공학윤리 = AI가 틀려도 책임은 확인하고 서명한 사람 · 공공 안전 최우선' },
        { kind: 'bullet', text: '주체성 = AI는 부조종사 · 기장은 나 · 할 수 있다 ≠ 해도 된다' },
        { kind: 'note', text: '휴식 10분 · 2:00 시작 · 다음 03 · AI 시대 항공 진로' },
      ],
      notes: '1분.' }),
    S({ id: 'g2-20', part: 2, partTitle: P2, layout: 'big',
      title: '쉬는 시간 10분',
      subtitle: '2:00 시작 · 다음 03 · AI 시대 항공 진로 — 끝까지 사람에게 남는 일',
      notes: '타이머 표시.' }),

    // ── 파트 3 · 3교시 (2:00–2:50) ──
    S({ id: 'g3-1', part: 3, partTitle: P3, layout: 'section',
      title: '03 · 3교시',
      subtitle: '2:00 – 2:50 · AI 시대 항공 진로' }),
    S({ id: 'g3-2', part: 3, partTitle: P3, layout: 'content',
      title: '항공 현장의 AI',
      blocks: [
        { kind: 'p', text: '3-1 · 항공 AI 분야' },
        { kind: 'bullet', text: '예측 정비(PHM) : 센서 데이터 분석 → 고장 전 부품 교체 시점 예측' },
        { kind: 'bullet', text: '비전 AI 외관 검사 : 카메라 · 드론 촬영 → 균열 · 찌그러짐 등 손상 탐지 보조' },
        { kind: 'bullet', text: '드론 · UAM : 자율 비행 · 경로 계획 · 기체 상태 감시' },
        { kind: 'bullet', text: '항공 관제 지원 · 디지털 트윈 · VR 정비 훈련' },
      ],
      notes: '2분. 모두 사람을 "보조"하는 방향. 국내외 항공사·제조사들이 예측 정비와 드론 검사를 도입·시험 중이라는 수준으로만 언급, 특정 수치 언급 자제.' }),
    S({ id: 'g3-3', part: 3, partTitle: P3, layout: 'content',
      title: '일의 두 층 = 반복 층 · 판단과 책임 층',
      blocks: [
        { kind: 'p', text: '3-2 · 일의 구조' },
        { kind: 'bullet', text: '반복 층 : 반복 촬영 · 1차 외관 검사 · 기록 · 재고 · 데이터 정리 → 로봇 · 드론 · 비전 AI로 대체될 가능성 큼' },
        { kind: 'bullet', text: '판단 · 책임 층 : 감항성 판단 · 최종 확인 · 서명 · 예외 상황 대응 · 안전 책임 · 설득 · 협업 → 사람에게 남음' },
        { kind: 'bullet', text: 'AI가 고장을 예측 · 제안 → 승인하고 책임지는 것은 자격을 갖춘 사람' },
        { kind: 'bullet', text: '연결 : 1교시 현장 지식 = 자산 · 2교시 책임 = 확인하고 서명한 사람' },
        { kind: 'callout', text: '관점 : 반복은 AI · 로봇에게 · 의사결정과 책임은 사람에게' },
      ],
      notes: '3분. 강사 관점 — 단순 반복은 로봇·AI로 대체될 예정, 의사결정과 책임은 사람에게 남음. 속도는 분야·규제마다 달라 "대체될 가능성이 큰"으로 표현. 좁은 기체 내부의 손작업·수리는 로봇이 어려워 사람에게 오래 남는 일(현장 기술의 가치 강조). 반대로 예측 정비처럼 AI가 판단을 "제안"하는 영역도 늘지만 승인·서명·책임은 사람. 항공 정비의 최종 확인·서명은 자격을 갖춘 사람의 권한과 책임. 들어가기 전 둘째 질문 회수.' }),
    S({ id: 'g3-4', part: 3, partTitle: P3, layout: 'big',
      title: '이 일은 AI · 로봇 쪽? 사람 쪽?',
      subtitle: '일의 두 층 분류 퀴즈 · 4문항',
      activityId: 'quiz-two-layers',
      notes: '3분. 문항당 15초. 정답 공개 때 "반복 층 / 판단·책임 층" 한 줄씩. 1번은 AI가 후보를 표시해도 최종 판정은 사람이라는 점 짚기.' }),
    S({ id: 'g3-5', part: 3, partTitle: P3, layout: 'twocol',
      title: '항공 정비사의 일 · 두 층으로 보기',
      blocks: [
        { kind: 'h', text: '반복 층 → AI · 로봇' },
        { kind: 'bullet', text: '반복 촬영 · 1차 외관 검사(드론 · 비전 AI)' },
        { kind: 'bullet', text: '센서 감시 · 이상 징후 알림(예측 정비)' },
        { kind: 'bullet', text: '기록 · 재고 · 매뉴얼 검색' },
        { kind: 'h', text: '판단 · 책임 층 → 사람' },
        { kind: 'bullet', text: '감항성 판단 · 최종 확인 · 서명' },
        { kind: 'bullet', text: 'AI 결과 검증 · 예외 상황 대응' },
        { kind: 'bullet', text: '실제 수리 · 손기술 · 팀 협업' },
      ],
      notes: '2분. 실제 수리·손기술은 로봇이 늘어도 당분간 사람 비중이 큰 영역 (좁은 기체 내부 작업은 특히). AI를 다룰 줄 아는 판단형 정비 인력 수요로 연결.' }),
    S({ id: 'g3-6', part: 3, partTitle: P3, layout: 'big',
      title: '10년 뒤 가장 기대되는 항공 AI 분야는?',
      subtitle: '하나 선택',
      activityId: 'poll-aviation-ai',
      notes: '2분. 1위 분야에 대해 한 줄 — 그 분야에서도 판단·책임은 사람 몫이라는 점 연결.' }),
    S({ id: 'g3-7', part: 3, partTitle: P3, layout: 'content',
      title: '항공 AI 진로 준비',
      blocks: [
        { kind: 'p', text: '3-3 · 진로' },
        { kind: 'bullet', text: '판단 역량 : 반복 기술 → 왜 이 절차인지 설명할 수 있는 이해' },
        { kind: 'bullet', text: '도메인 지식 : 전공 실습 · 정비 매뉴얼 읽기 · 자격증 준비' },
        { kind: 'bullet', text: 'AI 활용 : 바이브코딩 · 데이터 기초 · AI 결과 검증 습관' },
        { kind: 'bullet', text: '책임감 : 기록 · 보고 · Just Culture' },
        { kind: 'callout', text: '기준 : 반복 기술 → 판단 역량 + 도메인 지식 + AI 활용 + 책임감' },
      ],
      notes: '2분. 특정 학교·기업 추천 자제. 자격증 요건 등 세부 사항은 공식 기관 확인 안내.' }),
    S({ id: 'g3-8', part: 3, partTitle: P3, layout: 'big',
      title: '나의 항공 진로 윙 배지',
      subtitle: '10년 뒤 내 직업을 상징하는 배지 · 1인 3장 · 포트폴리오에 사용',
      activityId: 'image-future-me',
      notes: '4분. 실명 입력 금지 재안내. 만든 배지가 Lv.3 앱의 "내가 만든 그림"에 자동으로 뜬다고 안내.' }),
    S({ id: 'g3-9', part: 3, partTitle: P3, layout: 'big',
      title: '연습 단계 4 · 6분 — AI 진로 코치',
      subtitle: '관심 분야 입력 → 단계별 로드맵',
      activityId: 'tutor-career',
      blocks: [
        { kind: 'quote', text: '항공정비과 2학년이고 드론에 관심 있어. 코딩은 처음이야. 판단과 책임을 맡는 정비사가 되려면 뭘 준비해야 할지 로드맵 짜줘.' },
        { kind: 'callout', text: '합격 조건 : 고등학교 · 졸업 후 · 5년 뒤 3단계 로드맵 + 한 줄 목표' },
        { kind: 'note', text: '확인 포인트 : AI 추천 중 사실 확인이 필요한 정보 표시' },
      ],
      notes: '6분. 결과 로드맵과 한 줄 목표를 다음 Lv.3 앱에 옮겨 쓰도록 안내(복사해 두기).' }),
    S({ id: 'g3-10', part: 3, partTitle: P3, layout: 'big',
      title: '연습 단계 5 · 12분 — 나의 진로 포트폴리오',
      subtitle: '바이브코딩 Lv.3 · 앱 + 윙 배지 + 로드맵',
      activityId: 'vibe-lv3',
      blocks: [
        { kind: 'bullet', text: '1. 내 윙 배지와 한 줄 목표를 맨 위에' },
        { kind: 'bullet', text: '2. 3단계 로드맵을 타임라인으로' },
        { kind: 'bullet', text: '3. 1 · 2교시 앱 연결 또는 소개' },
        { kind: 'callout', text: '합격 조건 : 폰에서 열리는 포트폴리오 1페이지 완성' },
        { kind: 'note', text: '확인 포인트 : 실명 · 연락처 미포함 · 진행 : 9분 경과 시 마무리 안내' },
      ],
      notes: '12분. 이전 앱 자동 불러오기, 만든 윙 배지 선택 삽입 가능. 수정 8회까지. 완성 앱 링크는 개인 보관용.' }),
    S({ id: 'g3-11', part: 3, partTitle: P3, layout: 'big',
      title: '작품 자랑 투표',
      subtitle: '오늘 가장 마음에 든 나의 결과물은?',
      activityId: 'poll-showcase',
      notes: '2분. 앱 갤러리에서 우수작 1~2개 소개(본인 동의 후).' }),
    S({ id: 'g3-12', part: 3, partTitle: P3, layout: 'big',
      title: '종합 퀴즈 대회',
      subtitle: '7문항 · 3교시 전체 총정리 · 누적 점수로 최종 순위',
      activityId: 'quiz-final',
      notes: '4분. 문항당 15초, 자동 정답 공개. 최종 리더보드 상위 3명 발표.' }),
    S({ id: 'g3-13', part: 3, partTitle: P3, layout: 'content',
      title: '03 정리',
      blocks: [
        { kind: 'bullet', text: '일의 두 층 = 반복은 AI · 로봇 · 의사결정과 책임은 사람' },
        { kind: 'bullet', text: '진로 준비 = 판단 역량 + 도메인 지식 + AI 활용 + 책임감' },
        { kind: 'bullet', text: '결과물 = 폰에서 열리는 나의 진로 포트폴리오' },
      ],
      notes: '1분.' }),

    // ── 파트 4 · 마무리 ──
    S({ id: 'g4-1', part: 4, partTitle: P4, layout: 'content',
      title: '정리',
      blocks: [
        { kind: 'bullet', text: '이해 : AI의 개념 · 역사 · 생성형 AI 원리와 환각 · AI 윤리 쟁점 판단' },
        { kind: 'bullet', text: '제작 : 바이브코딩 앱 제작 → 검증 → 포트폴리오 완성' },
        { kind: 'bullet', text: '진로 : 반복은 AI · 로봇 · 판단과 책임 중심의 3단계 로드맵' },
        { kind: 'callout', text: '핵심 : AI가 만들고, 사람이 확인하고, 사람이 책임짐' },
      ],
      notes: '1분. 학습 목표와 1:1 대응 확인.' }),
    S({ id: 'g4-2', part: 4, partTitle: P4, layout: 'big',
      title: '소감 한마디',
      subtitle: '오늘 특강을 한 단어로 · 익명',
      activityId: 'poll-feedback',
      notes: '1분. 워드클라우드 띄운 채로 마무리 인사.' }),
    S({ id: 'g4-3', part: 4, partTitle: P4, layout: 'content',
      title: 'Q&A',
      blocks: [
        { kind: 'h', text: '질문' },
        { kind: 'p', text: 'seongho.cho@kodekorea.kr · kodekorea.kr · github.com/shain1912' },
        { kind: 'note', text: '미해결 질문 → 후속 자료로 회신' },
      ],
      notes: '2분. 시간 남을 때만. 300명 강당은 구두 질문 2~3개로 제한.' }),
    S({ id: 'g4-4', part: 4, partTitle: P4, layout: 'title',
      title: '특강 종료',
      subtitle: '다음 과제 : 오늘 만든 포트폴리오 앱에 새 기능 하나 추가',
      blocks: [
        { kind: 'p', text: '강사 조성호 · KODE KOREA(코드코리아) · seongho.cho@kodekorea.kr' },
      ],
      notes: '앱 링크는 강의실 종료 후에도 열림 → 개인 보관 안내.' }),
  ];
}
